project:
  type: website
  output-dir: docs


resources:
  - Baba.png
  - P38.json
  - P37.json
  - P36.json
  - P_Process.json


website:
  title: "介護福祉士問題演習"
  # 大学名などをフッター（ページ最下部）に入れる場合
  page-footer: 
    left: "©2026 新潟医療福祉大学 介護福祉学科"
    right: "AI 准教授 馬場 監修"
  
  navbar:
    background: "#f8dfe7" # ★ここをピンク（Zoom案内と同じ色）に
    collapse: true
    left:
      - href: index.qmd
        text: Home
      - text: "過去問"
        menu:
          - href: kako_38.qmd
            text: "第38回"
          - href: kako_37.qmd
            text: "第37回"
          - href: kako_36.qmd
            text: "第36回"
      - text: "パートごと"
        menu:
          - href: Part_A.qmd
            text: "Part A"
          - href: Part_B.qmd
            text: "Part B"
          - href: Part_C.qmd
            text: "Part C"


format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: quiz_multi.css  # 先頭の / を外す
    toc: true
    include-in-header:
      - text: |
          <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/dompurify@3.0.6/dist/purify.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/papaparse@5.4.1/papaparse.min.js"></script>
          <script src="quiz_multi.js"></script>
    include-after-body: header.html
