[build]
  command = """
  set -e

  curl -fL --retry 5 -o quarto.tar.gz https://quarto.org/download/latest/quarto-linux-amd64.tar.gz

  tar -xzf quarto.tar.gz

  # Find the extracted directory dynamically
  QUARTO_DIR=$(find . -maxdepth 1 -type d -name "quarto*" | head -n 1)

  echo "Quarto dir: $QUARTO_DIR"

  export PATH=$PWD/$QUARTO_DIR/bin:$PATH

  quarto --version

  quarto render
  """
  publish = "_site"