

## 人間の尊厳と自立

問題 1 次の記述のうち，介護福祉職がアドボカシー（advocacy）の視点から行う
対応として，最も適切なものを 1 つ選びなさい。
1 介護を行う前には，利用者に十分な説明をして同意を得る。
2 利用者の介護計画を作成するときに，他職種に専門的な助言を求める。
3 利用者個人の趣味を生かして，レクリエーション活動を行う。
4 希望を言い出しにくい利用者の意思をくみ取り，その実現に向けて働きかける。
5 視覚障害者が必要とする情報を，利用しやすいようにする。


問題 2 Ａさん（83 歳，女性，要介護 3 ）は，脳伷塞（cerebral infarction）の後遺症
で左
ひ だ り か た ま ひ
片麻痺があり，介護老人福祉施設で生活している。家族から，「できることは
自分で行ってほしい」と希望があり，Ａさんは自室から食堂まで車いすで自走する
ことを日課としている。
1 週間前から，介護福祉士養成施設の学生がＡさんのフロアで実習を開始した。
数日前からＡさんは実習生に，「今日は腕が痛いので，食堂まで車いすを押してく
ださい」と依頼するようになった。悩んだ実習生は，実習指導者に相談をした。
実習生に対する実習指導者の最初の助言として，最も適切なものを 1 つ選びなさ
い。
1 「Ａさんの腕は痛くないので，気にしないでください」
2 「どのようなときも，Ａさん自身で行ってもらうことが必要です」
3 「ご家族から自分で行うように，言われています」
4 「それは自立につながらないので，車いすを押さないでください」
5 「Ａさんが依頼する理由を，まず考えてみることが大切です」


## 人間関係とコミュニケーション

問題 3 人間関係と心理に関する次の記述のうち，適切なものを 1 つ選びなさい。
1 自己愛とは，自分という存在を，他人と区別して意識することである。
2 自己同一性の確立とは，自分とは何かという認識をもつことである。
3 自我とは，日常行動に影響を与える，表面化していない意識のことである。
4 自己覚知とは，コミュニケーションにおいて自分について話すことである。
5 自己中心性とは，自分の意思で自分の行動をコントロールすることである。

問題 4 Ａさん（80 歳，男性）は，有料老人ホームに入所することになった。一人
暮らしが長かったＡさんは，入所当日，担当の介護福祉職と話すことに戸惑ってい
る様子で，なかなか自分のことを話そうとはしなかった。介護福祉職は，一方的な
働きかけにならないように，Ａさんとコミュニケーションをとるとき，あいづちを
打ちながらＡさんの発話を引き出すように心がけた。
このときの，介護福祉職の対応の意図に当てはまるものとして，最も適切なもの
を 1 つ選びなさい。
1 互いの自己開示
2 コミュニケーション能力の評価
3 感覚機能の低下への配慮
4 認知機能の改善
5 双方向のやり取り

問題 5 次の記述のうち，介護福祉職のキャリアパスに関するものとして，最も適
切なものを 1 つ選びなさい。
1 介護計画を作成するときのポイントを明確にする。
2 介護福祉職の業務マニュアルを具体化する。
3 利用サービスに応じて求められる関係書類を検討する。
4 介護施設に必要な設備基準について確認する。
5 介護福祉職として必要な能力や経験を明確にする。
問題 6 Ｂ介護老人福祉施設に，学校を卒業したばかりの元気なＣ介護福祉職が加
わった。 2 か月後，ユニットリーダーが，「最近，Ｃ介護福祉職に笑顔が少ない。
いつもとちがう様子だ」と，フォロワーであるＤ介護福祉職に話した。Ｄ介護福祉
職はチームの一員として何ができるのかを考えた。
Ｄ介護福祉職が最初に行うフォロワーシップとして，最も適切なものを 1 つ選び
なさい。
1 Ｃ介護福祉職に対して，元気を出すように励ます。
2 ユニットリーダーが気になっていることを詳しく聞く。
3 Ｃ介護福祉職の状況をユニット内のほかのメンバーと速やかに共有する。
4 施設長に対して，何か指示を出すようにお願いする。
5 Ｃ介護福祉職に対して，介助方法について教える。


## 社会の理解

問題 7 社会福祉法に基づく社会福祉法人に関する次の記述のうち，適切なものを
1 つ選びなさい。
1 収益事業は禁止されている。
2 所轄庁は内閣府である。
3 設立時に所轄庁の認可は不要である。
4 評議員会を置く必要がある。
5 解散は禁止されている。
問題 8 次の記述のうち，定期巡回・随時対応型訪問介護看護の説明として，正し
いものを 1 つ選びなさい。
1 利用定員は， 9 人以下と定められている。
2 日中・夜間を通じて，提供するサービスである。
3 認知症対応型共同生活介護（認知症高齢者グループホーム）に入居する利用者に対
して，機能訓練を行うサービスである。
4 通い，泊まり，看護の 3 種類の組合せによるサービスである。
5 都道府県が事業者の指定，指導，監督を行うサービスである。

問題 9 Ａさん（48 歳，会社員）は，うつ症状から体調不良が続き，仕事を休むこ
とが増えたため，自主的に退職した。その後，体調は回復したが，再就職先がなか
なか見つからなかった。しばらく貯金で生活していたが，数か月後，生活を営むこ
とができなくなってしまった。頼れる親族はなく，生活保護を受給することにした。
この事例において，日本国憲法に基づいてＡさんに保障された権利として，最も
適切なものを 1 つ選びなさい。
1 団体交渉権
2 平等権
3 財産権
4 思想の自由
5 生存権
問題 10 次の記述のうち，保健所に関するものとして，正しいものを 1 つ選びなさ
い。
1 保健師助産師看護師法に基づいて設置されている。
2 すべての市町村に設置の義務がある。
3 業務には精神保健に関する事項が含まれている。
4 歯科衛生士を置かなくてはならない。
5 児童の一時保護を行う。

問題 11 地域包括支援センターの業務に関する記述として，正しいものを 1 つ選び
なさい。
1 地域ケア会議の開催
2 施設サービスのケアプランの作成
3 成年後見制度の申請
4 介護認定審査会の設置
5 地域密着型サービスの事業者の指導・監督
問題 12 Ｂさん（85 歳，男性，要支援 1 ）は，自宅で一人暮らしをしている。最近，
物忘れが多くなり， 1 か月前から地域支援事業の訪問型サービスを利用するように
なった。ある日，Ｂさんが，「これからも自宅で生活したいが，日中，話し相手が
いなくて寂しい」と介護福祉職に話した。
次のうち，Ｂさんに介護福祉職が勧めるサービスとして，最も適切なものを 1 つ
選びなさい。
1 認知症対応型共同生活介護（認知症高齢者グループホーム）
2 介護老人福祉施設
3 第一号通所事業（通所型サービス）
4 夜間対応型訪問介護
5 居宅療養管理指導

問題 13 介護保険制度に関する記述として，正しいものを 1 つ選びなさい。
1 第 1 号被保険者の保険料は，都道府県が徴収する。
2 第 1 号被保険者の保険料は，全国一律である。
3 第 2 号被保険者の保険料は，年金保険の保険料と合わせて徴収される。
4 財源には，第 1 号被保険者の保険料と第 2 号被保険者の保険料が含まれる。
5 介護保険サービスの利用者負担割合は，一律， 1 割である。
問題 14 障害者の雇用の促進等に関する法律に関する次の記述のうち，正しいもの
を 1 つ選びなさい。
1 2024 年度（令和 6 年度）の民間企業の法定雇用率は，2.5 ％である。
2 精神障害者は，法定雇用率の対象から除外されている。
3 2024 年度（令和 6 年度）に，障害者の雇用義務が生じるのは，従業員 101 人以上
の事業主である。
4 週所定労働時間が 10 時間以上 20 時間未満の労働は認められていない。
5 2024 年度（令和 6 年度）の事業主支援（助成金）は，2023 年度（令和 5 年度）以前と
同じである。

問題 15 「障害者総合支援法」のサービスに関する次の記述のうち，適切なものを 1
つ選びなさい。
1 介護給付費の支給を受けるときに，障害支援区分の認定は不要である。
2 短期入所は介護給付の 1 つである。
3 地域生活支援事業は，国が実施主体である。
4 自立支援給付は応益負担である。
5 行動援護は訓練等給付の 1 つである。
（注） 「障害者総合支援法」とは，「障害者の日常生活及び社会生活を総合的に支援す
るための法律」のことである。
問題 16 障害児支援に関する次の記述のうち，適切なものを 1 つ選びなさい。
1 サービスを受けるには，療育手帳の取得が必要である。
2 放課後等デイサービスは，子ども・子育て支援法に基づく支援である。
3 障害児通所支援の利用には，障害児支援利用計画の作成は不要である。
4 障害児入所支援は，すべての市町村が実施主体である。
5 保育所等訪問支援は，保育所等を訪問し，障害のある児童が集団生活に適応でき
るように専門的な支援を行う。

問題 17 次の記述のうち，サービス付き高齢者向け住宅に関するものとして，正し
いものを 1 つ選びなさい。
1 「高齢者住まい法」に基づく，高齢者のための住まいである。
2 65 歳以上の者が，市町村の措置によって入居する。
3 認知症高齢者を対象とした，共同生活の住居である。
4 食事サービスの提供が義務づけられている。
5 介護サービスの提供が義務づけられている。
（注） 「高齢者住まい法」とは，「高齢者の居住の安定確保に関する法律」のことである。
問題 18 Ｃさん（60 歳，男性）は，休日に自宅で趣味の家庭菜園の作業中に脳出血
（cerebral hemorrhage）を起こして救急搬送された。特に麻
ま ひ
痺はなく，その後，リハ
ビリテーション病院に転院した。現在は，高次脳機能障害（higher brain dysfunction）
の治療とリハビリテーションに専念している。
医療費を支払うときにＣさんが利用する制度として，最も適切なものを 1 つ選び
なさい。
1 介護保険制度
2 労働者災害補償保険制度
3 雇用保険制度
4 医療保険制度
5 年金制度

## こころとからだのしくみ

問題 19 次のうち，恐怖や不安，喜びなどの情動に関わる脳の機能局在の部位とし
て，正しいものを 1 つ選びなさい。
1 扁
へんとうたい
桃体
2 小脳
3 下垂体
4 海馬
5 視床下部

問題 20 次のうち，顔の感覚に関与する脳神経として，正しいものを 1 つ選びなさ
い。
1 嗅神経
2 三
さん
伹
さ
神
しん
経
けい
3 顔面神経
4 迷走神経
5 舌下神経

問題 21 次の記述のうち，鼻の構造と機能として，適切なものを 1 つ選びなさい。
1 鼻
び く う
腔は前鼻道・中鼻道・後鼻道に分かれる。
2 鼻毛は塵
ちり
や 埃
ほこり
を除去する。
3 鼻
び く う
腔の奥は喉頭に直接つながっている。
4 鼻
び く う
腔には毛細血管は少ない。
5 嗅細胞は外鼻孔にある。
問題 22 次のうち，歯周病（periodontal disease）の症状として，適切なものを 1 つ
選びなさい。
1 歯のくぼみの形成
2 歯の硬組織の軟化
3 歯髄の炎症・仏
とうつう
痛
4 歯のエナメル質の 侵
しんしょく
蝕
5 歯周ポケットの形成

問題 23 Ａさん（78 歳，女性）は，友人から口臭を指摘されて悩んでいる。また，
食事をするときに，「水分と一緒に食べないと飲み込みにくい」とも話している。Ａ
さんに歯の欠損，麻
ま ひ
痺はなく，ストレスの訴えもない。
次のうち，Ａさんのからだの中で，機能低下が考えられるものとして，最も適切
なものを 1 つ選びなさい。
1 咀
そしゃく
嚼
2 蠕
ぜんどううんどう
動運動
3 嗅覚
4 唾液分泌
5 胃液分泌
問題 24 皮膚の構造に関する次の記述のうち，最も適切なものを 1 つ選びなさい。
1 表皮の厚さは平均 2.0 mm である。
2 真皮には角質層がある。
3 外界と接する組織は表皮である。
4 皮脂腺は皮下組織にある。
5 表皮の最表面は基底層である。

問題 25 次のうち，高齢者が嗜
し こ う
好や温度覚の低下によって高温浴を希望した場合に，
説明すべき高温浴の特徴として，最も適切なものを 1 つ選びなさい。
1 血圧の上昇
2 腸
ちょう
蠕
ぜん
動
どう
の促進
3 腎機能の促進
4 副交感神経の亢
こうしん
進
5 心機能の抑制
問題 26 次のうち，食物の栄養素の大部分を吸収する部位として，正しいものを 1
つ選びなさい。
1 胃
2 小腸
3 直腸
4 横行結腸
5 Ｓ状結腸
問題 27 次の記述のうち，レム睡眠に関するものとして，最も適切なものを 1 つ選
びなさい。
1 記憶を整理し，定着させる。
2 脳を休息させる。
3 入眠初期に出現する。
4 成長ホルモンの分泌を促す。
5 深い眠りの状態である。

問題 28 Ｂさん（76 歳，男性）は，この数週間，日中に，「眠い」と訴えている。Ｂ
さんは毎日 15 時にコーヒー 1 杯を飲み，たばこを 1 本吸い，21 時に就寝する。夜
間の睡眠状態を数日間観察すると，睡眠中にぴくぴくと下肢が動いていることがた
びたびあった。起床後，手足に異常を感じるかをＢさんに確認したが，「特にない」
とのことだった。
次のうち，Ｂさんの睡眠障害の原因として，最も適切なものを 1 つ選びなさい。
1 ニコチン摂取
2 レム睡眠行動障害
3 レストレスレッグス症候群
4 カフェイン摂取
5 周期性四肢運動障害
問題 29 次のうち，呼吸中枢がある部位として，正しいものを 1 つ選びなさい。
1 大脳
2 中脳
3 小脳
4 延髄
5 脊髄

問題 30 次のうち，脳の機能停止を示す徴候に該当するものとして，適切なものを
1 つ選びなさい。
1 呼吸不全
2 溢
いつりゅうせいにょうしっきん
流 性 尿 失 禁
3 心停止
4 蠕
ぜんどううんどう
動運動の減弱
5 瞳孔散大・対光反射消失

## 発達と老化の理解

問題 31 次の記述のうち，子どもの標準的な成長として，適切なものを 1 つ選びな
さい。
1 1 歳半から 2 歳ごろに，ハイハイをして移動できるようになる。
2 生後 9 か月から 1 歳ごろに，指をさして自分の関心や欲求を他者に伝えられるよ
うになる。
3 子どもが使う言葉が急に増える語彙爆発は， 5 歳を過ぎたころに生じる。
4 人見知りの反応は， 2 歳を過ぎたころに生じる。
5 イヤイヤをしてすぐに泣く行動は，第二反抗期に生じる。
問題 32 次の記述のうち，神経性無食欲症（anorexia nervosa）に関するものとして，
最も適切なものを 1 つ選びなさい。
1 活動性が高まる。
2 学童期に最も生じやすい。
3 太ることへの恐怖はみられない。
4 低体重の深刻さを理解している。
5 多くが男性である。

問題 33 Ａさん（73 歳，男性）は，会社の役員として勤めていたが， 3 年前に退職
した。地域の老人クラブへの入会を勧められたが拒否している。毎年，敬老の日に
記念品が配布されても，不快感を示して受け取らない。退職後も会社の状況を気に
していて，後輩とときどき連絡をとっている。Ａさんは，身体が衰えることに強い
不安を感じて，筋力トレーニングを毎日行っている。会社の後輩から，「いつも
若々しいですね」と言われることに喜びを感じている。
ライチャード（Reichard, S.）による，引退後の男性の 5 つの適応タイプのうち，
Ａさんに相当するものとして，適切なものを 1 つ選びなさい。
1 外罰（憤慨）型
2 内罰（自責）型
3 円熟（成熟）型
4 自己防衛（装甲）型
5 ロッキングチェアー（安楽椅子）型
問題 34 次の記述のうち，結晶性知能に関する説明として，最も適切なものを 1 つ
選びなさい。
1 感覚や運動に基づく知能である。
2 過去に得た知識を活用して問題を解決する能力である。
3 40～50 歳で急激に低下する。
4 知識や文化の影響よりも，生理的な老化の影響を受けやすい。
5 その場で新しい問題を解決する能力である。

問題 35 次の記述のうち，加齢に伴う感覚機能の変化として，最も適切なものを 1
つ選びなさい。
1 皮膚感覚が敏感になる。
2 高音域の聴力が高まる。
3 暗順応の時間が延長する。
4 味覚が敏感になる。
5 嗅覚が敏感になる。
問題 36 Ｂさん（74 歳，女性）は，地方で一人暮らしをしている。持病はなく，認
知機能の異常もない。ダンスサークルに通い，近所との付き合いも良好で，今の暮
らしに満足している。最近，白髪が増え，友人との死別もあり，年をとったと感じ
ている。ある日，一人息子（50 歳，未婚）から，東京で一緒に住むことを提案され
た。Ｂさんは，「ここには知り合いがいるが，東京には誰もいない。ここが一番い
い」と言った。すると息子は，Ｂさんに，「年をとると頑固になる。あと数年したら
認知症（dementia）になるかもしれないので，自分と一緒に暮らすべきだ」と言った。
次のうち，Ｂさんに関する記述として，最も適切なものを 1 つ選びなさい。
1 Ｂさんには，老性自覚はみられない。
2 Ｂさんには，友人との死別による悲嘆がみられる。
3 Ｂさんは，今，住んでいる環境や生活に適応できていない。
4 Ｂさんには，エイジズム（ageism）の考え方がみられる。
5 Ｂさんには，住み慣れた環境や仲間を喪失することへの不安がみられる。

問題 37 次の記述のうち，サクセスフル・エイジング（successful aging）として，
適切なものを 1 つ選びなさい。
1 長生きすることが，最大の目的である。
2 一人暮らしで，周囲の人と交流をしないようにしている。
3 膝に痛みがあるので，一日中ベッド上で過ごすようにしている。
4 難聴があるので，補聴器をつけてパソコン教室に通い始めた。
5 歌を上手に歌えなくなったので，カラオケに誘われても行かないようにしている。
問題 38 次のうち，老年症候群に直接関わる疾患として，最も適切なものを 1 つ選
びなさい。
1 高血圧症（hypertension）
2 糖尿病（diabetes mellitus）
3 骨
こつそしょうしょう
粗鬆症（osteoporosis）
4 心筋伷塞（myocardial infarction）
5 脂質異常症（dyslipidemia）

## 認知症の理解

問題 39 次の記述のうち，2019 年（令和元年）の認知症施策推進大綱に関する説明
として，最も適切なものを 1 つ選びなさい。
1 「共生」と「予防」を車の両輪として施策を推進していく。
2 「予防」とは，「認知症（dementia）にならない」という意味である。
3 「認知症高齢者等にやさしい地域づくり」を推進する 7 つの柱が示された。
4 「普及啓発・本人発信支援」として，家族が積極的に本人の意思を代弁することが
示された。
5 策定後は，毎年施策の進捗を確認することが示された。
問題 40 Ａさん（84 歳，女性，要介護 3 ）は，アルツハイマー型認知症（dementia
of the Alzheimer’s type）で，介護老人福祉施設に入所している。赤ちゃんの人形
を持っていて，「はなちゃん」と呼んで話しかけている。
昼食のため，介護福祉職が居室を訪問すると，Ａさんは不安そうな顔で，「はな
ちゃんがいなくなった。どこへ連れて行ったの？返して」と大声を出した。人形は
Ａさんのロッカーの上に置かれていた。
Ａさんに対する介護福祉職の最初の声かけとして，最も適切なものを 1 つ選びな
さい。
1 「私を疑っているんですか」
2 「置いた場所を忘れたんですか」
3 「心配ですね，一緒に探しませんか」
4 「ご飯を食べてから探してはどうですか」
5 「ロッカーの上にあるのが見えないんですか」

問題 41 認知症（dementia）の高齢者にみられる，せん妄に関する記述として，適
切なものを 1 つ選びなさい。
1 覚醒レベルが重度に低下した状態である。
2 症状の変動が少ないことが特徴である。
3 夜間よりも日中に生じやすいことが特徴である。
4 認知機能障害がみられることはまれである。
5 関与する因子を特定することが重要である。
問題 42 次の記述のうち，アルツハイマー型認知症（dementia of the Alzheimer’s
type）の特徴として，適切なものを 1 つ選びなさい。
1 近時記憶（新しい記憶）の障害は，初期から始まる。
2 特徴的な症状として幻視がある。
3 脳にアミロイドβが沈着し始めると，すぐに発症する。
4 歩行障害が多く現れるのは，初期の段階である。
5 嚥
えん
下
げ
障
しょう
害
がい
が多く現れるのは，初期の段階である。
問題 43 次のうち，認知症（dementia）のリスクを高める要因として，最も適切な
ものを 1 つ選びなさい。
1 身体活動
2 不飽和脂肪酸の摂取
3 歯がなくなることによる咀
そ し ゃ く き の う
嚼機能の低下
4 難聴による補聴器の使用
5 ボランティア活動

問題 44 次のうち，全般的な認知機能を評価する尺度であり，30 点満点で 20 点以
下を認知症の目安とするものとして，正しいものを 1 つ選びなさい。
1 バーセルインデックス（Barthel Index）
2 改訂長谷川式認知症スケール（HDS-R）
3 ＦＡＳＴ（Functional Assessment Staging）
4 認知症高齢者の日常生活自立度判定基準
5 臨床的認知症尺度（ＣＤＲ：Clinical Dementia Rating）
問題 45 次の記述のうち，「認知症（dementia）の人の日常生活・社会生活における
意思決定支援ガイドライン」（2018 年（平成 30 年）（厚生労働省））で示されている，
意思決定支援として，最も適切なものを 1 つ選びなさい。
1 認知症（dementia）の人の家族の意思を支援することである。
2 意思決定支援者は特定の職種に限定される。
3 一度，意思決定したら，最後まで同じ内容で支援する。
4 看取りの場面になってから支援を開始する。
5 身振りや表情の変化も意思表示として読み取る努力を最大限に行う。
問題 46 次の記述のうち，回想法として，最も適切なものを 1 つ選びなさい。
1 肩や背中から優しくゆっくりと触れる。
2 共感を通して，認知症（dementia）の人が体験している現実を受け入れる。
3 見当識を高めるために，時間や場所，現在の状況を説明する。
4 昔の写真や音楽を活用して，記憶を活性化する。
5 残存能力を活用し，共同作業を通して仲間をつくる。

問題 47 次の記述のうち，認知症疾患医療センターの説明として，適切なものを 1
つ選びなさい。
1 事業の実施主体は，市町村である。
2 都道府県ごとに， 1 か所の設置が義務づけられている。
3 認知症（dementia）の鑑別診断を行う。
4 主に認知症（dementia）が進行した人の入院治療を行う。
5 介護保険法に定められている。
問題 48 Ｂさん（87 歳，男性）は，一人暮らしである。玄関前で，脱水で倒れてい
るところを発見され，救急搬送された。入院中，認知症（dementia）の疑いがある
行動が見られた。Ｂさんは，「自宅で暮らしたい」と強く希望していた。退院後，Ｂ
さんは外出して自宅に戻れなくなることがあった。近所の人たちが，Ｂさんの生活
を心配して，地域包括支援センターに相談した結果，認知症初期集中支援チームが
編成された。
次の記述のうち，Ｂさんに対して認知症初期集中支援チームが行う支援として，
最も適切なものを 1 つ選びなさい。
1 金銭管理を行う。
2 支援方針を検討する。
3 居宅サービス計画書を作成する。
4 介護保険サービスを契約する。
5 法定後見を行う。


## 障害の理解

問題 49 次のうち，ＩＣＦ（International Classification of Functioning, Disability
and Health：国際生活機能分類）の社会（人生）レベルに該当するものとして，正し
いものを 1 つ選びなさい。
1 心身機能・身体構造
2 活動
3 参加
4 機能障害
5 活動制限
問題 50 次の記述のうち，障害者のエンパワメントに関するものとして，最も適切
なものを 1 つ選びなさい。
1 障害のある人が障害のない人と同等に生活し，活動する社会を目指す。
2 専門職が主導し，障害がある人は受動的に支援を受ける。
3 障害のある人が自らの能力や長所に気づき，課題に対応する。
4 障害のある人が，主体性や人権が守られないことに耐える。
5 障害のある人が，医学的リハビリテーションを受ける。

問題 51 次のうち，クローン病（Crohn disease）にみられる特徴的な症状として，
最も適切なものを 1 つ選びなさい。
1 視力低下
2 栄養障害
3 咳
がいそう
嗽
4 運動失調
5 関節痛
問題 52 次の記述のうち，遂行機能障害の特徴として，最も適切なものを 1 つ選び
なさい。
1 些
さ さ い
細なことですぐに興奮して怒鳴る。
2 新しい知識を覚えることが困難である。
3 ぼんやりして周囲に注意を向け続けることが困難である。
4 行動を計画して実行することが困難である。
5 言葉の表出や理解が困難である。
問題 53 視覚障害の特徴と視覚障害者の生活支援に関する次の記述のうち，最も適
切なものを 1 つ選びなさい。
1 ロービジョンは，視覚情報をまったく得られない状態である。
2 中途視覚障害者は，先天性の障害に比べて障害を受容しやすい。
3 白
はくじょう
伺 には，視覚に障害があることを周囲に知らせる役目がある。
4 視覚障害を補うために，ペットの犬と一緒に外出する。
5 視覚障害者は，ガイドヘルパーの利用はできない。

問題 54 Ａさん（76 歳，女性）は，パーキンソン病（Parkinson disease）と診断され，
日常生活動作（Activities of Daily Living：ＡＤＬ）は，車いすやベッド上で全介助
である。最近，食事に時間がかかって嫌がるようになり，かすれ声が目立つように
なった。
次のうち，現在のＡさんに対して介護福祉職が留意すべきこととして，最も適切
なものを 1 つ選びなさい。
1 安静時振戦
2 筋固縮
3 仮面様顔貌
4 誤
ご え ん
嚥
5 便秘
問題 55 聴覚障害者の特徴や支援の方法に関する次の記述のうち，最も適切なもの
を 1 つ選びなさい。
1 要約筆記によって意思疎通を補う。
2 軽度の聴覚障害を「ろう」という。
3 フラッシュベルは周囲の音を増幅させて伝える。
4 手話は意思の伝達に役立たない。
5 両耳の聴力レベルが 40 dB で身体障害者手帳が交付される。

問題 56 Ｂさん（24 歳，男性）は，母親と二人暮らしで，小学生のときに注意欠陥
多動性障害と疑われていた。Ｂさんは，最近になって昼夜を問わずゲームを続け，
朝起きられずにアルバイトを無断で休むことが増えた。
次のうち，Ｂさんの母親が相談する機関として，最も適切なものを 1 つ選びなさ
い。
1 ハローワーク（公共職業安定所）
2 難病情報センター
3 認知症カフェ
4 放課後等デイサービス
5 発達障害者支援センター

問題 57 次の記述のうち，「障害者差別解消法」の合理的配慮に沿った対応として，
最も適切なものを 1 つ選びなさい。
1 車いすの身体障害者から，陳列棚にある商品を見せてほしいと言われたが，口頭
で商品を説明した。
2 聴覚障害者の手話による注文がわからなかったので，最も人気のあるメニューを
出した。
3 盲導犬を連れた視覚障害者が来店したが，動物嫌いの客から苦情を言われると思
い，犬は店の中に入れないように頼んだ。
4 役所に相談に来た精神障害者から，多くの人の中だと不安になると言われたため，
帰宅してもらった。
5 知的障害者から申し出があったので，会議に参加するための資料をわかりやすい
言葉に直して，事前に口頭で説明した。
（注） 「障害者差別解消法」とは，「障害を理由とする差別の解消の推進に関する法律」
のことである。
問題 58 レスパイトケアの望ましいあり方に関する記述として，最も適切なものを
1 つ選びなさい。
1 障害者はサービスを利用せずに生活するべきである。
2 利用中，家族は自宅で休まなくてはならない。
3 家族が障害者を預けて旅行に行くことは認められない。
4 家族の休息が目的なので，障害者の施設利用は宿泊に限定される。
5 家族が休息している間も，障害者が自分らしく過ごせるようにする。

## 医 療 的 ケ ア


問題 59 次の記述のうち，成人に対する<ruby>救急蘇生法<rt>きゅうきゅうそせいほう</rt></ruby> での胸骨圧迫の方法として，最も適切なものを 1 つ選びなさい。
1 呼吸が確認できない場合は，すぐに圧迫を始める。
2 圧迫する部位は，胸骨の左側である。
3 実施者の両手を重ねて，指先で圧迫する。
4 圧迫の深さは，胸が 10 cm 沈むようにする。
5 1 分間に 60 回を目安に圧迫する。

問題 60 次の記述のうち，<ruby>痰<rt>たん</rt></ruby>を<ruby>喀出<rt>かくしゅつ</rt></ruby>する仕組みに関するものとして，正しいものを 1 つ選びなさい。
1 呼吸器官の内部は乾燥した状態になっている。
2 気管の内部の表面には<ruby>絨毛<rt>じゅうもう</rt></ruby>があり，分泌物の侵入を防いでいる。
3 分泌物は，咽頭で吸収される。
4 <ruby>痰<rt>たん</rt></ruby>は，<ruby>咳<rt>せき</rt></ruby>や<ruby>咳払<rt>せきばら</rt></ruby>いによって排出される。
5 <ruby>咳<rt>せき</rt></ruby>は，下垂体にある <ruby>咳中枢<rt>せきちゅうすう</rt></ruby>咳によっておこる反射運動である。

問題 61 次の記述のうち，介護福祉士が行う<ruby>口腔内<rt>こうくうない</rt></ruby>の<ruby>喀痰吸引<rt>かくたんきゅういん</rt></ruby>の方法として，最も適切なものを 1 つ選びなさい。
1 吸引圧は，利用者の体調によって介護福祉士が決める。
2 吸引圧をかけた状態で，吸引チューブを挿入する。
3 口蓋垂まで吸引チューブを挿入する。
4 吸引チューブを回転させながら<ruby>痰<rt>たん</rt></ruby>を吸引する。
5 吸引後は洗浄水を吸引し，清浄綿でチューブを拭く。


問題 62 次の記述のうち，消化器症状の説明として，正しいものを 1 つ選びなさい。
1 腹部膨満感は，腹部が張る感覚のことである。
2 しゃっくり（ 吃
きつぎゃく
逆 ）は，胸膜の刺激で起こる現象である。
3 胸やけは，飲食物による食道の熱傷のことである。
4 げっぷ（噯気）は，咽頭にたまった空気が排出されることである。
5 嘔
お う き
気は，胃や腸の内容物が，食道を逆流して口外に吐き出されることである。

問題 63 Ａさん（80 歳，女性）は，脳伷塞（cerebral infarction）の後遺症で左
ひ だ り か た ま ひ
片麻痺
があり，介護老人保健施設に入所して在宅復帰に向けた訓練をしている。嚥
えん
下
げ
障
しょう
害
がい
もあるため，経鼻経管栄養による栄養摂取をしているが，経口摂取できないことで
イライラしてチューブを抜去したことがある。医師からは一時的な治療であると説
明を受けて同意していた。
経管栄養中に介護福祉士が訪室すると，チューブを触りながら，「自分の口から
食べたいから，このチューブを抜いてほしい。見た目も良くない」と訴えがあった。
看護師に連絡し，チューブが抜けていないことを確認してもらった。
このときのＡさんへの介護福祉士の対応として，最も適切なものを 1 つ選びなさ
い。
1 チューブを抜かないようにＡさんの右手を固定する。
2 経管栄養が早く終わるように滴下速度を調節する。
3 医師や看護師にＡさんの思いを伝える。
4 Ａさんに胃ろうの造設を提案する。
5 Ａさんに経口摂取を提案する。


## 介護の基本

問題 64 介護福祉に関連する法律に関する次の記述のうち，適切なものを 1 つ選び
なさい。
1 「高齢者虐待防止法」は，福祉六法の 1 つである。
2 「障害者総合支援法」は，障害者基本計画の策定を義務づけている。
3 社会福祉法によって，社会福祉士の定義が規定されている。
4 介護保険法は，国民の共同連帯の理念に基づいて介護保険制度を設けている。
5 医師法によって，介護福祉の業務の一部として医行為が認められている。
（注）1 「高齢者虐待防止法」とは，「高齢者虐待の防止，高齢者の養護者に対する支
援等に関する法律」のことである。
2 「障害者総合支援法」とは，「障害者の日常生活及び社会生活を総合的に支援
するための法律」のことである。

問題 65 社会福祉士及び介護福祉士法に関する次の記述のうち，適切なものを 1 つ
選びなさい。
1 資質向上のために， 5 年に 1 回，資格更新研修を受けなければならない。
2 社会福祉士の業務を介護福祉士が行うことは禁じられている。
3 介護福祉士の信用を傷つける行為をしてはならない。
4 介護福祉士は，その業を辞した後は秘密保持義務が解除される。
5 介護福祉士国家試験に合格した日から，介護福祉士を名乗ることができる。
問題 66 Ａさん（75 歳，女性）は， 3 か月前に，血管性認知症（vascular dementia）
を発症し，軽度の左
ひ だ り か た ま ひ
片麻痺で伺
つ え ほ こ う
歩行となり，要介護 3 と認定された。Ａさんは，料
理が大好きで，娘と一緒に食事を作ることを楽しみに生活していた。 1 か月前から
認知症（dementia）が進行し，ユニット型介護老人福祉施設に入所した。Ａさんは
夕方になると，「ご飯の支度をしないといけないから帰ります」と言いながら，興奮
して歩き回る様子がみられるようになった。
Ａさんへの介護福祉職の対応として，最も適切なものを 1 つ選びなさい。
1 居室に伴をかけて，自室で過ごしてもらう。
2 介護福祉職と一緒に，夕食の準備をしてもらう。
3 伺
つえ
を預かり，低めの丸椅子に座ってもらう。
4 介護福祉職の判断で，向精神薬を服用してもらう。
5 ここがＡさんの自宅であることを，理解してもらう。

問題 67 ＩＣＦ（International Classification of Functioning, Disability and Health：
国際生活機能分類）における「参加」と「活動」の 2 つが関連した，認知症の人の支援
に関する記述として，最も適切なものを 1 つ選びなさい。
1 若年性アルツハイマー型認知症（dementia of the Alzheimer’s type with early
onset）があり，治療している。
2 認知症カフェに通い，体操をしている。
3 近所に住む長男が，買物を代行している。
4 自宅にある広い庭を，バリアフリー化している。
5 見当識障害があり，ＧＰＳ装置を身に着けている。
問題 68 次の記述のうち，介護保険制度における訪問介護員（ホームヘルパー）が行
うサービス内容として，最も適切なものを 1 つ選びなさい。
1 利用者が大切にしている庭の植木に，水やりをする。
2 利用者が長年飼っている猫のペットフードを，購入してくる。
3 掃き掃除をする習慣のある利用者と一緒に，寝室をほうきで掃除する。
4 利用者と一緒に，近所のラーメン屋に行く。
5 利用者のクレジットカードを預かって，買物を代行する。

問題 69 次の記述のうち，介護従事者を守る法制度として，正しいものを 1 つ選び
なさい。
1 労働安全衛生法では，年に 1 回以上の健康診断を行うことを義務づけている。
2 労働者災害補償保険法では，労働時間，賃金，休暇などの労働条件を定めている。
3 環境基本法では，快適な職場環境の形成の促進を定めている。
4 介護休業は，対象家族 1 名につき，毎年 93 日間を取得できる。
5 出生時育児休業は，子の出生後から 8 週間取得できる。
問題 70 Ｂさん（68 歳，女性，要介護 1 ）は，ヨーロッパで生まれ育ち，50 歳のと
きに日本人と結婚した。65 歳で夫と共に日本で暮らすようになったが，日本語は
十分に理解できない。半年前に，脳伷塞（cerebral infarction）を起こし，利き手に
麻
ま ひ
痺があり，立ち上がりも不安定である。現在は，介護老人保健施設に入所し，在
宅復帰へ向けたリハビリテーションを行っている。Ｂさんはこれまでの生活様式を
守り，自宅で自分のペースで食事ができるようになりたいと希望している。
次の記述のうち，Ｂさんへの介護福祉職の対応として，最も適切なものを 1 つ選
びなさい。
1 入所中は母語を使わずに，日本語を話すように伝える。
2 居室の床に布団を敷いて，寝起きができるようにする。
3 自分で食事ができるように，自助具の使用状況を確認する。
4 ほかの利用者と同じ時間に食べ終えるように伝える。
5 日本の生活に合わせるように，余暇活動の内容は介護福祉職が判断する。

問題 71 次の記述のうち，チームアプローチに関するものとして，適切なものを 1
つ選びなさい。
1 介護福祉職が利用者のところに行って，相談，支援を行う。
2 障害者が，地域の資源を活用して，共生社会の実現を目指す。
3 複数の専門職が共通の目標に向かって協働し，課題解決に取り組む。
4 利用者に代わって，専門職がサービスを決定する。
5 当事者が集まって体験談を話し，共に支えあう。
問題 72 介護保険施設における防災対策に関する次の記述のうち，最も適切なもの
を 1 つ選びなさい。
1 介護福祉士は，災害派遣福祉チームで活動することが義務づけられている。
2 介護福祉士は，防災スキル向上のために，防災士の資格取得が義務づけられている。
3 災害対策基本法に基づき，個別避難計画の作成が施設長に義務づけられている。
4 一般的に，飲料水と非常食は 1 日分の備蓄が義務づけられている。
5 災害時等に備えて，業務継続計画（ＢＣＰ：Business Continuity Plan）の策定が
義務づけられている。
問題 73 次のうち，結核（tuberculosis）の予防対策に該当するものとして，最も適
切なものを 1 つ選びなさい。
1 便座のアルコール消毒
2 肺炎球菌ワクチンの接種
3 紫外線を避けた生活
4 年に 1 回の胸部Ｘ線検査
5 50℃以上の温水によるリネン類の洗濯




## コミュニケーション技術

問題 74 次の記述のうち，利用者とのコミュニケーションの場面で用いる要約の技
法として，適切なものを 1 つ選びなさい。
1 開かれた質問をして，利用者の気持ちを明らかにした。
2 共感しながら話を聞き，利用者の気持ちを受け止めた。
3 話の途中でうなずき，利用者の気持ちに同意した。
4 話の内容を総合的にまとめて返し，利用者の気持ちを整理した。
5 自己覚知を図り，利用者との人間関係の形成に努めた。
問題 75 次の記述のうち，利用者と家族の意向が異なるとき，家族とのコミュニ
ケーションにおいて介護福祉職が留意すべき点として，適切なものを 1 つ選びなさ
い。
1 家族に支援方針を決めてもらう。
2 家族を通して利用者の意向を聴き取る。
3 家族と話す機会を別に設ける。
4 家族にカウンセリングを行うことを意識する。
5 家族を説得する。

問題 76 Ａさん（80 歳，男性，要介護 3 ）は，介護老人福祉施設に入所している。
アルツハイマー型認知症（dementia of the Alzheimer’s type）が進行している。あ
る日の昼食時，介護福祉職がＡさんに配膳すると，「お金はこれしかありません。
足りますか」と小さくたたまれたティッシュペーパーを渡してきた。
このときのＡさんに対する介護福祉職の対応として，最も適切なものを 1 つ選び
なさい。
1 ティッシュペーパーは，口の周りが汚れたら拭くものだと伝える。
2 ティッシュペーパーが不足しているサインとして受け止める。
3 飲食店での会計の場面であると認識して対応する。
4 食事に集中するように促す。
5 小遣いの増額を家族に相談する。
問題 77 構音障害のあるＢさんは，現在発語訓練を実施中である。ある日，介護福
祉職に対して，「おあんで，あつがおごれた」と訴えた。介護福祉職は，Ｂさんの発
語をうまく聞き取れず，「もう一度，言ってください」と伝えた。Ｂさんは，自身の
発語で会話を続けようとしているが，介護福祉職には，その内容を十分に理解する
ことができなかった。
このときの，Ｂさんに対する介護福祉職の判断として，最も適切なものを 1 つ選
びなさい。
1 Ｂさんは言葉の意味の理解に支障があるため，会話の継続は困難である。
2 発音が苦手なため，短い言葉でゆっくり話してもらう必要がある。
3 話す意欲があるため，開かれた質問が有効である。
4 発語訓練の効果がみられないため，訓練を中止する必要がある。
5 Ｂさんの言葉が聞き取れないため，会話を中断する必要がある。


問題 78 Ｃさん（55 歳，男性）は，知的障害がある。 3 か月前に，施設から居宅で
の一人暮らしに移行し，現在は，居宅介護（ホームヘルプサービス）を利用しながら
生活している。ある日，Ｃさんが，「ゴミ，分けて捨てるの，難しいよ」と言うので，
室内に分別収集の説明書を貼って，カレンダーに収集日を書くことにした。そして，
介護福祉職は，「この説明書とカレンダーを見て，捨てるといいですよ」とＣさんに
伝えた。その後，Ｃさんは努力していたが，分別できなかったゴミが少しずつ増え
ていった。
次のうち，Ｃさんにかける介護福祉職の最初の言葉として，最も適切なものを 1
つ選びなさい。
1 「ゴミでいっぱいになる前に，適切に捨てられるようになりましょう」
2 「説明書とカレンダーをよく見てください」
3 「ゴミが増えてきて，気持ち悪いですね」
4 「がんばっていれば，上手にできるようになりますよ」
5 「ゴミ捨ては難しいですよね。できることをいっしょに考えましょう」
問題 79 介護保険サービスにおける記録に関する次の記述のうち，最も適切なもの
を 1 つ選びなさい。
1 記録に含まれないものとして食事チェック表がある。
2 介護記録は介護福祉職の意見を中心に記録する。
3 調査・研究目的で記録を利用することは避ける。
4 主観的情報と客観的事実は区別しないで記録する。
5 利用者は記録の閲覧を請求することができる。



## 生活支援技術


問題 80 高齢者に配慮した居室環境に関する次の記述のうち，最も適切なものを 1
つ選びなさい。
1 夏は高齢者が発汗してから冷房を使用する。
2 暖房を使用するときは除湿機を併用する。
3 冷房を使用するときは換気を控える。
4 温度は介護福祉職の感覚で調整する。
5 冬はトイレの温度を居室の温度に近づける。
問題 81 次の記述のうち，介護の現場において，レクリエーション活動で実施する
アイスブレーキングの効果として，最も適切なものを 1 つ選びなさい。
1 参加者の緊張感を軽減することができる。
2 活動内容を毎回固定して実施することができる。
3 介護福祉職の負担を軽減することができる。
4 利用者の参加を義務づけることができる。
5 勝敗を楽しむことができる。

問題 82 次の記述のうち，介護福祉職が行う身じたく・整容の介護として，最も適
切なものを 1 つ選びなさい。
1 ベッド上で行う口
こうくう
腔ケアは，ガーグルベースンを用いる。
2 総義歯の洗浄は，歯みがき剤を用いる。
3 耳
じ こ う
垢の除去は，ピンセットを用いる。
4 ベッド上で行う洗顔は，冷水に浸して絞ったタオルを用いる。
5 浴室で行う洗髪は，ドライシャンプーを用いる。
問題 83 次の記述のうち，障害のある人への事故防止の対応として，最も適切なも
のを 1 つ選びなさい。
1 パーキンソン病（Parkinson disease）の人には，低めのベッドを用意する。
2 認知症（dementia）の人には，ガスコンロを用意する。
3 在宅酸素療法中の人のそばでは，喫煙しない。
4 視覚障害のある人には，洗体用に頭受け台を用意する。
5 聴覚障害のある人には，補高便座を用意する。
問題 84 次のうち，右
み ぎ か た ま ひ
片麻痺の利用者が多
た て ん づ え
点伺を使用して 3 動作歩行を開始すると
きに，介護福祉職が行う説明として，適切なものを 1 つ選びなさい。
1 「伺
つえ
，右足，左足の順で歩きましょう」
2 「伺
つえ
，左足，右足の順で歩きましょう」
3 「右足，左足，伺
つえ
の順で歩きましょう」
4 「左足，伺
つえ
，右足の順で歩きましょう」
5 「左足，右足，伺
つえ
の順で歩きましょう」


問題 85 ノーリフティングケアに関する次の記述のうち，最も適切なものを 1 つ選
びなさい。
1 仰
ぎ ょ う が い
臥位（背
は い が い
臥位）の利用者を抱え上げて，端座位にする。
2 仰
ぎ ょ う が い
臥位（背
は い が い
臥位）の利用者を手前に引きよせて，ストレッチャーに移乗する。
3 端座位の利用者の体幹を抱きかかえて，車いすに移乗する。
4 端座位の利用者にスライディングボードを使用して，車いすに移乗する。
5 立位が困難な端座位の利用者に回転移動盤を使用して，車いすに移乗する。
問題 86 次の記述のうち，左
ひ だ り か た ま ひ
片麻痺の利用者を右
み ぎ そ く が い
側臥位から端座位にするときの介
護として，最も適切なものを 1 つ選びなさい。
1 利用者に左手でベッド柵をつかむように伝える。
2 利用者に右肘を支点にして上体を起こしてもらう。
3 利用者の右脚をベッドから下ろす。
4 利用者の頸
け い ぶ
部を支えて上体を起こす。
5 端座位の利用者の右側に立って上体を支える。
問題 87 口
こうくう
腔ケアに関する次の記述のうち，最も適切なものを 1 つ選びなさい。
1 うがいは，顔貌を整える。
2 歯みがきは，感染予防になる。
3 口
こうくうない
腔内の乾燥は，口臭を予防する。
4 唾液腺マッサージは，唾液の分泌を抑える。
5 咀
そ し ゃ く き の う
嚼機能の向上のために，タッピングを行う。

問題 88 次の記述のうち，口
こうくう
腔ケアを実施するときの留意点として，最も適切なも
のを 1 つ選びなさい。
1 実施中は，利用者に顎を上げた姿勢をとってもらう。
2 総義歯は，上顎から下顎の順に外してもらう。
3 歯みがきの前に，うがいを行ってもらう。
4 歯ブラシは，大きく動かして磨いてもらう。
5 舌ブラシは，舌先から咽頭に向かって動かしてもらう。
問題 89 次の記述のうち，介護が必要な人への熱中症対策のために，介護福祉職が
行う水分補給の対応として，最も適切なものを 1 つ選びなさい。
1 のどが渇いてから，水分を取るように伝える。
2 水でむせるときは，ゼリーの提供を控える。
3 起床時は，水分摂取を控えるように伝える。
4 食事のときの水分は，一日の水分摂取量から除く。
5 汗の量が多いときは，塩分を含んだ飲み物を勧める。

問題 90 Ａ さ ん（75 歳， 男 性 ）は， 1 年 前 に 前 頭 側 頭 型 認 知 症（frontotemporal
dementia）と診断され，現在は，認知症対応型共同生活介護（認知症高齢者グルー
プホーム）に入居している。若い頃から食べることが好きである。現在，咀
そしゃく
嚼や
嚥
え ん げ き の う
下機能の低下はなく，スプーンを使い，自分で食べている。最近，飲み込む前に
次々と食べ物を口に入れることが増えた。
次の記述のうち，Ａさんの現在の状態に合わせた食事の介護として，最も適切な
ものを 1 つ選びなさい。
1 取っ手つきのコップを準備する。
2 食器に少量ずつ盛りつけて提供する。
3 すべての料理をテーブルの上に並べる。
4 大きなスプーンに変更する。
5 手で持って食べられる物を準備する。
問題 91 次の記述のうち，パーキンソン病（Parkinson disease）で上肢の震えはあ
るが，自力摂取が可能な利用者の食事の介護として，最も適切なものを 1 つ選びな
さい。
1 食事後に口
こうくうない
腔内のアイスマッサージを行う。
2 片側の縁が高くなっている皿を準備する。
3 上半身を後ろに 20 度程度倒すように伝える。
4 食器の置いてある位置を説明する。
5 踵
かかと
を床から浮かすように伝える。

問題 92 次の記述のうち，入浴の作用を生かした，高齢者への入浴の介護として，
最も適切なものを 1 つ選びなさい。
1 食事は，入浴直前に摂取する。
2 高血圧の人には，42℃以上の湯につかってもらう。
3 浴槽の中では，関節運動を促す。
4 心疾患（heart disease）のある人には，肩まで湯につかってもらう。
5 個浴の浴槽内では，足を浮かせてもらう。
問題 93 次の記述のうち，下肢筋力が低下して介護を必要とする人の入浴に適した
環境として，最も適切なものを 1 つ選びなさい。
1 浴室の入口は開き戸にする。
2 床から浴槽の縁までの高さは 20 cm にする。
3 縦に長く，浅めの洋式の浴槽にする。
4 浴槽の縁の幅は 20 cm にする。
5 浴槽への出入りのために，水平および垂直の手すりを設置する。
問題 94 次の記述のうち，体調不良で入浴できない片
か た ま ひ
麻痺の利用者に対して，ベッ
ド上で行う全身清拭の方法として，最も適切なものを 1 つ選びなさい。
1 清拭時は，窓を開けて行う。
2 洗面器には，40℃程度のお湯を準備する。
3 最初に，腹部から清拭する。
4 背部は，患側を下にした側
そ く が い
臥位にして拭く。
5 蒸しタオルで拭いた後は，乾いたタオルで水分を拭き取る。


問題 95 次のうち，同居の高齢者におむつを使用する家族介護者に対する，介護福
祉職の説明として，最も適切なものを 1 つ選びなさい。
1 「使用する本人の羞恥心に気を配りましょう」
2 「尿失禁を防ぐことができます」
3 「尿量を気にせずに， 1 日中同じおむつを使うことができます」
4 「おむつを着けると，安心して排
はいせつ
泄ができます」
5 「家族の都合に合わせて，おむつを使いましょう」
問題 96 次の記述のうち，ポータブルトイレを使用するときの排
はいせつ
泄の介護として，
最も適切なものを 1 つ選びなさい。
1 ポータブルトイレの下に新聞紙を敷く。
2 ベッドで臥
がしょう
床している状態で，ズボンや下着をおろす。
3 ポータブルトイレには，前かがみになって座ってもらう。
4 排
はいせつ
泄が終わるまで，ポータブルトイレの後ろに立って待つ。
5 排
は い せ つ ご
泄後の陰部の清拭は，ベッドの上で行う。
問題 97 次の記述のうち，介護福祉職が行うことのできる，坐
ざ
薬
やく
（座薬）を用いた介
護として，最も適切なものを 1 つ選びなさい。
1 膣
ちつ
から挿入する坐
ざ
薬
やく
（座薬）が扱える。
2 坐
ざ
薬
やく
（座薬）は，あたたかな場所で保管する。
3 坐
ざ
薬
やく
（座薬）は，とがっていない方から挿入する。
4 腹部に力を入れるよう促しながら，坐
ざ
薬
やく
（座薬）を挿入する。
5 下剤以外の坐
ざ
薬
やく
（座薬）挿入は，先に排
はいせつ
泄を済ませてから行う。

問題 98 次の記述のうち，調理における基本調味料の効果や使い方として，適切な
ものを 1 つ選びなさい。
1 砂糖は，塩より先に入れると，食物に甘みが浸透しやすくなる。
2 塩は，食物のうま味を増し，照りを出す。
3 酢は，食物の水分を引き出し，保存性を高める。
4 しょうゆは，食物のくさみを抜き，肉を柔らかくする。
5 みそは，味付けの最初に入れると，特有の香りが逃げない。
問題 99 食品の保存に関する次の記述のうち，最も適切なものを 1 つ選びなさい。
1 賞味期限の切れた未開封の缶詰は，すぐに廃棄する。
2 ウインナーには，消費期限が記載されている。
3 前日調理して常温保存した肉入りカレーは，再加熱する。
4 りんごを冷蔵庫で保存するときは，ビニール袋に入れて密封する。
5 冷凍食品は，一度解凍しても再冷凍すれば長期間の保存が可能である。
問題 100 次の記述のうち，衣類の保管方法として，適切なものを 1 つ選びなさい。
1 衣装ケースで保管するときは，たたんだ衣類の下に防虫剤を入れる。
2 ドライクリーニング後の衣類は，ビニールを外さずに保管する。
3 汚れのひどい衣類は，介護福祉職の判断で廃棄する。
4 湿気を含んだ衣類は，たたんで引き出しに保管する。
5 絹製品は，タンスの上部に保管する。




## 介護過程

問題 106 次の記述のうち，介護過程を展開する目的として，最も適切なものを 1 つ
選びなさい。
1 家族が抱える生活課題の解決
2 個別ケアに基づく利用者の自立支援
3 介護福祉職の職業倫理の向上
4 利用者と家族の信頼関係の構築
5 介護福祉職と他職種の連携の促進
問題 107 生活課題に関する記述として，最も適切なものを 1 つ選びなさい。
1 家族の立場から検討する。
2 利用者のニーズを判断の基盤にする。
3 利用者の要望を 1 つに集約する。
4 介護福祉職の主観を尊重する。
5 生命の危機よりも利用者の意向を優先する。

問題 108 次の記述のうち，介護過程の展開における評価の説明として，最も適切な
ものを 1 つ選びなさい。
1 他の利用者と比較して評価する。
2 短期目標の評価によって，介護過程の展開を終了する。
3 目標の達成状況を評価する。
4 介護計画の実施後に評価日を検討する。
5 介護計画を修正した場合は，評価を省略する。

問題 109 次のうち，介護保険制度のサービス担当者会議におけるサービス提供責任
者の役割として，最も適切なものを 1 つ選びなさい。
1 会議の主催
2 居宅サービス計画の原案の説明
3 他職種が実施したサービス内容の評価
4 訪問介護計画の作成に要した時間の報告
5 訪問介護計画の作成に必要な情報の確認

次の事例を読んで，問題 110，問題 111 について答えなさい。
〔事 例〕
Ａさん（78 歳，男性，要介護 1 ）は，一人暮らしで，脳伷塞（cerebral infarction）を
発症し入院した。その後，リハビリテーションを経て，自宅に戻った。利き手の右手
に麻
ま ひ
痺が残ったため，左手を使った調理の自立を目的に，訪問介護（ホームヘルプ
サービス）を利用することになった。サービス利用時は，訪問介護員（ホームヘル
パー）の協力を得ながら，孫からプレゼントされた包丁を使って，調理に取り組んで
いた。
ある日，好物の牛肉をうまく押さえることができず，切ることができなかった。す
ると，Ａさんは包丁を置き，部屋で横になってしまった。心配した訪問介護員（ホー
ムヘルパー）が声をかけ，バイタルサインを確認したところ変化はなかった。Ａさん
は，「右手が思うように動いてくれない。悔しい。でも，もう一度ひとりで作れるよ
うになりたい」と話した。
次の日，Ａさんは，「今日も手伝って」と訪問介護員（ホームヘルパー）に話した。

問題 110 調理中にＡさんが包丁を置き，部屋で横になってしまった行動に対する解
釈として，最も適切なものを 1 つ選びなさい。
1 体調不良による休憩
2 食材に対する不満
3 調理に対する興味の喪失
4 包丁に対する不満
5 調理がうまくできないことに対する苛
い ら だ
立ち
問題 111 訪問介護計画の修正を目的としたカンファレンスで，訪問介護員（ホーム
ヘルパー）が提案する内容として，最も適切なものを 1 つ選びなさい。
1 訪問介護員（ホームヘルパー）による調理の代行
2 担当する訪問介護員（ホームヘルパー）の交代
3 配食サービスの利用
4 調理に関する福祉用具の活用
5 訪問回数の削減


## 総合問題


次の事例を読んで，問題 114 から問題 116 までについて答えなさい。
〔事 例〕
Ａさん（70 歳，男性）は，妻と二人で暮らしている。旅行や釣りが趣味で，会社員
として勤務していたころは，活動的な生活を送っていた。66 歳のときにパーキンソ
ン病（Parkinson disease）と診断されたが，内服治療が開始され，症状はあまり気に
ならなかった。 1 年前から顔の表情が乏しくなり，歩行開始時に，はじめの一歩が出
にくくなった。 3 か月前からは，歩き始めると方向転換が難しく，急に止まることが
できないことがある。
Ａさんは，今後の生活について相談するために，地域包括支援センターに行った。
センターで対応してくれたＢ主任介護支援専門員は，介護福祉士としての実務経験が
豊富だった。Ａさんは信頼して，気になっていたことをすべて話すことができた。Ａ
さんは，要介護認定を申請することを勧められ，後日，市役所に行き，要介護認定の
申請を行った。


問題 114 現在のＡさんの症状に該当するホーエン・ヤール重症度分類として，最も
適切なものを 1 つ選びなさい。
1 ステージⅠ
2 ステージⅡ
3 ステージⅢ
4 ステージⅣ
5 ステージⅤ
問題 115 要介護認定を申請してから 2 週間が経過した。Ａさんは要介護認定の認定
結果が届かないことが気になった。そこで，以前に対応してくれたＢ主任介護支援
専門員に電話で相談した。
次のうち，Ｂ主任介護支援専門員の応答として，最も適切なものを 1 つ選びなさ
い。
1 「次の受診時に主治医に相談しましょう」
2 「通常 1 か月程度かかるので，あと 2 週間くらい待ってみましょう」
3 「以前に自宅に来てくれた認定調査員に相談しましょう」
4 「念のためにもう一度要介護認定を申請してください」
5 「通常であれば認定結果は出ていると思います」

問題 116 最近，Ａさんは急に体の動きが悪くなる時間帯があり，不安を感じた。そ
こでＡさんは，週に 2 回利用している訪問介護員（ホームヘルパー）に相談した。相
談を受けた訪問介護員（ホームヘルパー）はＡさんに，日々の症状の変化とその時間，
さらにもう一点をメモして，医師に伝えるようにと助言した。
日々の症状の変化とその時間に加えて，Ａさんが医師に伝える内容として，最も
優先度の高いものを 1 つ選びなさい。
1 服薬の時間
2 起床の時間
3 食事の時間
4 排便の時間
5 入浴の時間

次の事例を読んで，問題 117 から問題 119 までについて答えなさい。
〔事 例〕
Ｃさん（90 歳，女性）は，動物好きで長年ペットのオウムを飼っている。 5 年前に
夫が亡くなったときも，ペットが大きな心の支えになった。 2 年前，身体の衰えから
買物や調理などの家事が難しくなり，一人暮らしが困難になったので，ペットと入所
できる健康型有料老人ホームに入所した。
最近Ｃさんは，毎週楽しみにしていたレクリエーションがある曜日や時間を忘れて
しまう，トイレの場所がわからず失禁するなどの症状が繰り返し生じるようになって
きた。心配した娘がＣさんと病院を受診したところ，アルツハイマー型認知症
（dementia of the Alzheimer’s type）と診断を受けた。
健康型有料老人ホームでは対応が困難になってきたため，心配した娘はＣさんが入
所できる施設に移ることを検討し始めた。
問題 117 次のうち，最近のＣさんの症状に該当するものとして，最も適切なものを
1 つ選びなさい。
1 妄想
2 見当識障害
3 失語
4 遂行機能障害
5 観念失行

問題 118 娘はＣさんの病状を心配して，「お父さんが残してくれた貯金があるから，
もっとお母さんのお世話をしてくれる施設に移ろう」と提案した。Ｃさんは，「ペッ
トと一緒に暮らせなくなるのは嫌だ」とつぶやき，うつむいた。困った娘は健康型
有料老人ホームの介護福祉士に相談した。
次のうち，娘への介護福祉士の応答として，最も適切なものを 1 つ選びなさい。
1 「Ｃさんがペットを大事にしている意思を尊重してはいかがですか」
2 「Ｃさんが新しい施設に行くことが最優先です」
3 「あなたの意向を優先してはいかがですか」
4 「Ｃさんがペットを飼うことは優先度の高いニーズとは言えません」
5 「Ｃさんが新しい施設に行くことを受け入れるように説得してください」
問題 119 Ｃさんと娘は介護福祉士と相談し，希望に沿った施設を見つけることがで
きた。
次のうち，Ｃさんが入所する施設として，最も適切なものを 1 つ選びなさい。
1 経過的軽費老人ホーム（Ｂ型）
2 介護医療院
3 介護老人保健施設
4 養護老人ホーム
5 介護付有料老人ホーム

次の事例を読んで，問題 120 から問題 122 までについて答えなさい。
〔事 例〕
Ｄさん（男性，障害支援区分 4 ）は，ベッカー型筋ジストロフィー（Becker muscular
dystrophy）である。自宅で家族と生活をしている。Ｄさんは，食事は自立している
が，排
はいせつ
泄，入浴に介護が必要である。歩行はできず，移動は電動車いすを使用してい
る。絵を描くことが趣味であり，日中は創作活動に取り組んでいる。
これまでＤさんは自宅で家族の介護を受けながら生活してきたが，Ｄさんの身体機
能の低下に伴い，家族の介護負担が増えたため，居宅介護を利用することになった。
問題 120 Ｄさんの疾患で生じる病態として，適切なものを 1 つ選びなさい。
1 筋線維の変性
2 運動神経の変性
3 網膜の変性
4 自己免疫の低下
5 脳細胞の変性

問題 121 Ｅ居宅介護事業所に勤務するＦ介護福祉職は，Ｄさん宅を初回訪問するに
あたりフェイスシートのジェノグラムを確認した。
以下のジェノグラムからＦ介護福祉職が把握した内容として，適切なものを 1 つ
選びなさい。
51
51 48
21
77
47
7477
1 Ｄさんは，Ｄさんの母親と同居している。
2 Ｄさんには息子がいる。
3 Ｄさんの兄は結婚している。
4 Ｄさんの父親は生存している。
5 Ｄさんの妻には兄弟姉妹がいる。

問題 122 Ｄさんが居宅介護を利用してから数年が経過し，Ｄさんの身体機能は徐々
に低下して，着替えに時間がかかるようになった。Ｄさんは自分のことはできるだ
け自分で行いたいという思いがあり，時間がかかっても自分で着替えをしていた。
ある日，ＤさんはＦ介護福祉職に，「着替えをすると疲れてしまい，絵を描くこ
とができない」とつぶやいた。Ｆ介護福祉職は，「着替えは私たちや家族の介護を利
用して，Ｄさんは好きな絵を描いたらいいのではないですか」と伝えた。その後，
Ｄさんは介護福祉職と家族の介護を利用して，短時間で着替えを済ませ，絵を描く
ことに専念できるようになった。
Ｆ介護福祉職が発言した自立観を示した人物として，最も適切なものを 1 つ選び
なさい。
1 ヴィクトール・フランクル（Frankl, V.）
2 バンク－ミケルセン（Bank-Mikkelsen, N.）
3 エド・ロバーツ（Roberts, E.）
4 フェリックス・バイステック（Biestek, F.）
5 ミルトン・メイヤロフ（Mayeroff, M.）

次の事例を読んで，問題 123 から問題 125 までについて答えなさい。
〔事 例〕
Ｇさん（38 歳，女性）は，母親（65 歳）と暮らしていた。両側性感音難聴（sensorineural
hearing loss）があり，雑音がある場所では話を聞き取りにくい。相手の口の動きや表
情から会話の内容を理解することはできる。Ｇさんは，脳伷塞（cerebral infarction）
を発症し，左
ひ だ り か た ま ひ
片麻痺で車いすの生活となり，障害支援区分 4 と認定された。母親によ
る介護が難しくなったため，障害者支援施設に入所することになった。
Ｇさんは，写真を撮ることが好きで，施設で近くの公園に出かけたときに，介護福
祉職に手伝ってもらいながら好きな風景を撮影している。Ｇさんは，その写真をアル
バムにして，母親にプレゼントしたいと考えている。
ある日，Ｇさんから，「アルバムを作りたい。飾りの付け方やメッセージの書き方
を教えてほしい」と相談があった。介護福祉職は，Ｇさんとアルバムを作ることにし
た。
問題 123 次のうち，Ｇさんが施設入所支援と同時に利用している障害福祉サービス
として，適切なものを 1 つ選びなさい。
1 自立生活援助
2 療養介護
3 短期入所
4 生活介護
5 居宅介護

問題 124 次のうち，Ｇさんの難聴の原因となっている損傷部位に該当するものとし
て，最も適切なものを 1 つ選びなさい。
1 内耳から聴神経
2 外耳道から中耳
3 耳介から中耳
4 耳介から外耳道
5 耳介

問題 125 次の記述のうち，Ｇさんに介護福祉職がアルバムの作り方を説明するとき
に配慮することとして，最も適切なものを 1 つ選びなさい。
1 Ｇさんの左側に座る。
2 閉じられた質問を用いる。
3 小さな声で話す。
4 Ｇさんの好きな音楽を流す。
5 1 対 1 で向かい合って話す。




















































