
# 38

## 人間の尊厳と自立


問題 1 社会福祉の理念を発展させた人物に関する次の記述のうち，適切なものを
1 つ選びなさい。
1 バンク-ミケルセン（Bank-Mikkelsen, N.）は，「ソーシャルロール・バロリゼー
ション（Social Role Valorization）」を提唱した。
2 ニィリエ（Nirje, B.）は，「ノーマライゼーション（normalization）の 8 つの原理」
を提唱した。
3 ヴォルフェンスベルガー（Wolfensberger, W.）は，「エーデル改革」を提唱した。
4 リッチモンド（Richmond, M.）は，「ケースワークの 7 原則」を提唱した。
5 エリクソン（Erikson, E.）は，「自立生活運動の理念」を提唱した。

問題 2 Ａ さ ん（62 歳， 男 性， 要 介 護 2 ）は， 2 年 前 に 筋 萎 縮 性 側 索 硬 化 症
（amyotrophic lateral sclerosis：ＡＬＳ）と診断された。妻と自宅で過ごしたいと希
望し，訪問介護（ホームヘルプサービス）と訪問看護を利用している。最近，症状が
進行し，サービス担当者会議で，Ａさんは，「人工呼吸器はつけないで，最期まで
自宅で生活したい」と言った。
会議のあと，妻は訪問介護員（ホームヘルパー）に，「夫にはなかなか言えないの
ですが，一日でも長く一緒にいたいので，私は人工呼吸器をつけてほしいと思って
います」と気持ちを伝えた。
次のうち，Ａさんの妻に対する訪問介護員（ホームヘルパー）の提案として，最も
適切なものを 1 つ選びなさい。
1 「会議で話されていたＡさんの意思が大切なので，尊重しませんか」
2 「私にはわからないので，医師に決めてもらってはどうですか」
3 「Ａさんに人工呼吸器をつけてもらったほうがいいですよね」
4 「Ａさんとお互いの気持ちを話し合う時間をつくりませんか」
5 「病院や施設の情報がほしいと介護支援専門員に伝えてはどうですか」

## 介 護 の 基 本

問題 3 介護施設における介護ロボットに関する次の記述のうち，最も適切なもの
を 1 つ選びなさい。
1 導入した施設は，人員配置基準が撤廃される。
2 使用方法は，職員個人の判断で行う。
3 導入することによって，利用者の自立支援や生活の質の向上が期待される。
4 導入の目的は，職員と利用者とのかかわりを最小限に抑えることである。
5 導入によって，職員の巡回は不要になる。
問題 4 次の記述のうち，指定避難所での要配慮者に対する生活支援として，最も
適切なものを 1 つ選びなさい。
1 避難所内の情報提供には，音声やピクトグラム（pictogram）も取り入れる。
2 避難所内では，二次避難に備えて土足で過ごしてもらう。
3 食事は，被災者の平等性，公平性の観点から同じものを提供する。
4 トイレは，感染予防のために和式便器が望ましい。
5 生活範囲は，区画されたスペースに限定する。

問題 5 ユニバーサルデザイン（universal design）の 7 原則に関する次の記述のう
ち，最も適切なものを 1 つ選びなさい。
1 安全で使いやすいデザインにする。
2 要介護高齢者を対象とする。
3 個別対応より標準化を優先する。
4 介護福祉職にとって操作しやすいことを優先する。
5 デザインの美しさを優先する。
問題 6 Ａさん（51 歳，男性，障害支援区分 5 ）は，知的障害がある。共同生活援
助（グループホーム）で生活をしている。日中は，生活介護を利用して軽作業を行っ
ている。Ａさんは，タオルに強いこだわりを持っていて，なじみの店で自分が選ん
だタオルしか使用しない。これまでタオルは，両親と買いに行っていたが，両親が
高齢になり行けなくなった。Ａさんの両親から，サービス管理責任者に，「強いこ
だわりがあるので，いつも行く店で本人にタオルを選ばせてほしい。何か良いサー
ビスはありませんか」と相談があった。
次の記述のうち，サービス管理責任者の助言として，最も適切なものを 1 つ選び
なさい。
1 店までの移動に不安があるため，同行援護を勧める。
2 身体機能の維持・向上のために，自立訓練（機能訓練）を勧める。
3 一人で外出できるように，自発的活動支援を勧める。
4 自立した日常生活が送れるように，自立生活援助を勧める。
5 本人が買物に行けるように，行動援護を勧める。

問題 7 次の記述のうち，介護保険制度における一人暮らしの要支援者を支える
サービスの内容として，適切なものを 1 つ選びなさい。
1 夜間を安心して過ごすために，夜間対応型訪問介護を利用する。
2 自宅で安全に移動するために，介護予防住宅改修を利用する。
3 趣味のカラオケに行くために，小規模多機能型居宅介護を利用する。
4 身元保証や死後の財産処分のために，高齢者等終身サポート事業を利用する。
5 金銭管理のために，日常生活自立支援事業を利用する。
問題 8 Ａさん（91 歳，女性，要支援 2 ）は，長年診療所の医師として地域医療に
貢献してきた。婚姻歴はなく，診療所敷地内の自宅で 3 匹の猫と暮らしている。85
歳で医師を引退した後も，近隣にはＡさんを慕う地域住民が多く，定期的に，「先
生，元気にしてますか」とＡさんの自宅を訪ねている。
Ａさんは昨年から歩行の不安を訴え，現在は地域住民の見守りのほか，訪問型
サービスを週 2 回利用している。人の世話になることに慣れていない様子もあるが，
最期まで自宅で暮らすことを望んでいる。
次の記述のうち，Ａさんの生活史を尊重した訪問介護員（ホームヘルパー）の声か
けとして，最も適切なものを 1 つ選びなさい。
1 「 3 匹の猫は，今後は地域の皆さんに預けましょう」
2 「近所の方の力も借りて，この地域で暮らしていけるように考えていきましょう」
3 「介護を受けることにも，今後は慣れてください」
4 「医師であったことは忘れて，私たちを頼ってください」
5 「一人暮らしで自宅で最期を迎えるのは，不安がありますよね」

問題 9 次の記述のうち，介護老人保健施設における在宅復帰に向けたカンファレ
ンスで，介護福祉士が連携する職種の役割として，最も適切なものを 1 つ選びなさ
い。
1 歯科衛生士が，義歯を作成する。
2 看護師が，車いすを貸与する。
3 介護支援専門員（ケアマネジャー）が，訪問介護計画を作成する。
4 福祉用具専門相談員が，下肢の機能訓練をする。
5 作業療法士が，自宅の玄関の段差を確認する。
問題 10 次の記述のうち，介護老人福祉施設におけるリスクマネジメントとして，
最も適切なものを 1 つ選びなさい。
1 安全対策担当者を置き，事故発生予防のための委員会を定期的に開催する。
2 家族からの苦情は，介護福祉職が，その場で解決する。
3 利用者の私物を壊したときは，介護福祉職の自己判断で弁償する。
4 入浴介助時のインシデントの報告は，職員間の口頭による伝達に統一する。
5 事故防止のため，地域のお祭りへの参加は控える。
問題 11 次の記述のうち，介護現場におけるレジオネラ菌の感染対策として，最も
適切なものを 1 つ選びなさい。
1 感染者の衣類は，熱湯で煮沸消毒する。
2 提供する食品は，加熱調理を徹底する。
3 循環式浴槽は，塩素系薬剤を使用して消毒する。
4 ドアノブは，次亜塩素酸ナトリウム液で消毒する。
5 家庭用加湿器のタンクの水は，常に貯めておく。

問題 12 介護福祉職が受けるストレスチェック制度に関する次の記述のうち，最も
適切なものを 1 つ選びなさい。
1 3 年に 1 回の実施が義務づけられている。
2 労働者数が常時 100 名の事業場は受検が免除される。
3 結果は労務管理を行う介護主任へ提供され，面接指導に活用する。
4 心理的な負担の程度を把握するためのものである。
5 高ストレスと判定された場合は，産業医による治療が必須である。

## 社会の理解

問題 13 民法の親族に関する次の記述のうち，正しいものを 1 つ選びなさい。
1 三親等内の血族を家族と規定している。
2 六親等内の姻族を親族と規定している。
3 いとこは互いに扶養する義務があると規定している。
4 同居する親族は互いに扶
たす
け合わなければならないと規定している。
5 養子と養親の間には，親族関係は生じない。
問題 14 次の記述のうち，「令和 4（2022）年 国民生活基礎調査」（厚生労働省）にお
ける，高齢者に関する調査結果として，適切なものを 1 つ選びなさい。
1 65 歳以上の者のいる世帯の世帯構造で最も多いのは，親と未婚の子のみの世帯
である。
2 高齢者世帯は 5 割以上を占めている。
3 要介護者等と同居の主な介護者の年齢の組合せでは，65 歳以上同士が約 6 割を
占めている。
4 介護が必要となった理由の第 1 位は，骨折・転倒である。
5 1 世帯当たりの平均所得金額では，高齢者世帯では 600 万円を超えている。

問題 15 Ａさん（78 歳，女性）は，一人暮らしである。家事や買物は，時間はかか
るが，できるだけ自分で取り組んでいる。近くに頼れる親族がいないため，緊急時
にすぐに通報できる公共サービスを利用している。Ａさんは，定期的に市の窓口や
地域包括支援センターに今後の生活支援について相談している。近所には，毎日散
歩を一緒にしている友人グループがいて，散歩に来ない仲間がいると訪問して声を
かけあっている。
次のうち，Ａさんの生活を支える自助に該当するものとして，最も適切なものを
1 つ選びなさい。
1 Ａさんが身辺のことを，時間をかけてもやること
2 緊急時にすぐに通報できる公共サービスを利用していること
3 市の窓口の職員が相談に応じること
4 地域包括支援センターの職員が相談に応じること
5 散歩仲間が声をかけあっていること
問題 16 介護保険制度における介護サービス利用に関する次の記述のうち，適切な
ものを 1 つ選びなさい。
1 65 歳未満の者は，保険給付の対象外である。
2 保険給付には，支給限度額がある。
3 要介護認定の有効期限は，原則として 3 か月である。
4 保険給付による福祉用具の貸与は，要介護 3 以上の者が対象である。
5 地域包括支援センターに相談する前に，要介護認定を受ける必要がある。

問題 17 次の記述のうち，障害者福祉の歴史的展開として，最も適切なものを 1 つ
選びなさい。
1 国際連合の障害者の権利に関する条約の影響を受け，障害者基本法に「社会的障
壁の除去」が規定された。
2 第二次世界大戦後 5 年以内に，優生保護法が廃止された。
3 「精神薄弱者福祉法」の制定によって，知的障害者の入所施設からの地域移行が推
進された。
4 社会福祉基礎構造改革によって，高齢者より先に障害者の福祉制度が利用契約制
度となった。
5 身体障害，知的障害，精神障害のうち，福祉に関する法律の制定が最も早かった
のは知的障害である。
（注） 「精神薄弱者福祉法」とは，現在の知的障害者福祉法のことである。
問題 18 次の記述のうち，障害者福祉に関係する機関やシステムとして，最も適切
なものを 1 つ選びなさい。
1 地域活動支援センターは，補装具の判定を行う。
2 基幹相談支援センターには，介護福祉士の配置が義務となっている。
3 都道府県は，身体障害者更生相談所を設置しなければならない。
4 都道府県は，障害支援区分の認定を行う。
5 利用者負担の額は，市町村障害福祉計画によって決められる。

問題 19 障害者虐待防止に関する次の記述のうち，適切なものを 1 つ選びなさい。
1 養護者による虐待が疑われる障害者を発見した場合，都道府県へ通報する義務が
ある。
2 著しく拒絶的な対応は身体的虐待に当てはまる。
3 使用者による障害者虐待は含まれない。
4 行政職員が障害者福祉施設等に，立ち入り調査を行うことは許されていない。
5 虐待を発見した障害者福祉施設従事者が通報した場合，業務上の守秘義務違反に
はならない。
問題 20 Ａさん（82 歳，女性，要介護 1 ）は，自宅で一人暮らしをしている。外出
機会が少ないＡさんを心配して，民生委員が定期的に見守りを行っている。ある日，
民生委員から地域包括支援センターに，「Ａさんのように，家に閉じこもりがちな
要介護者が増えている。民生委員だけでは十分な見守りができない」と相談があった。
次の記述のうち，地域包括支援センターの職員の対応として，最も適切なものを
1 つ選びなさい。
1 高齢者本人による相談が原則のため，Ａさん自身が相談に来るように促す。
2 介護サービスを利用するため，Ａさんのケアプランを作成する。
3 フォーマルな社会資源の活用を優先し，民生委員のかかわりを制限する。
4 地域ケア会議において，関係者と地域課題について話し合う。
5 要介護者の実態を把握するために，介護保険審査会を設置する。

問題 21 法定後見制度に関する次の記述のうち，正しいものを 1 つ選びなさい。
1 65 歳未満の者は利用することができない。
2 判断能力が十分ある者には，後見人をつけることができない。
3 市町村長は，後見開始の審判を請求することができない。
4 法人を後見人に選任することはできない。
5 後見人は財産管理を行うことはできない。
問題 22 有料老人ホームに関する次の記述のうち，適切なものを 1 つ選びなさい。
1 入居する高齢者に，介護，食事の提供，家事，健康管理のうち 1 つ以上のサービ
スを提供する。
2 状況把握サービスと生活相談サービスの提供が義務づけられている。
3 自立した高齢者は，入居の対象外である。
4 共生型サービスとして，指定を受けることができる。
5 介護保険制度の指定対象外である。
問題 23 生活困窮者自立支援法に関する記述のうち，適切なものを 1 つ選びなさい。
1 障害者は対象から除外されている。
2 生活困窮者自立相談支援事業は，社会福祉法人へ委託できない。
3 生活困窮者自立相談支援事業は，市にとって任意事業である。
4 生活困窮者住居確保給付金の支給は，市にとって必須事業である。
5 都道府県の責務は規定されていない。

問題 24 次の記述のうち，生活保護制度における補足性の原理として，適切なもの
を 1 つ選びなさい。
1 申請に基づいて保護を行う。
2 国の定める基準によって測定された需要をもとに保護を行う。
3 個人の必要に応じてできるだけ早く保護を行う。
4 資産・能力を活用した上で保護を行う。
5 世帯を単位として保護を行う。

## 人間関係とコミュニケーション

問題 25 新人職員のＡさん（20 歳）は，子どもの頃からの夢だった介護福祉職にな
り，がんばって働いていた。ただ，介護の技術をもっと学ぶ必要があるといつも感
じていた。ある日，利用者Ｂさんに，「Ａさんじゃダメだ，別の人を呼んで」と言わ
れて，ショックを受けた。悩むうちに利用者とかかわりたくないと感じるようにな
り，眠れなくなってしまった。
次の記述のうち，このような状況にあるＡさんが，ストレスを取り除くためにま
ず行うべき対処方法として，最も適切なものを 1 つ選びなさい。
1 つらさから逃げず，学びが足りないことを自覚する。
2 介護の技術がうまくなるために，全力で取り組む。
3 眠れるように，毎晩飲酒する。
4 上司や同僚などに悩みを話して，助言を受ける。
5 介護福祉職には向かないと判断して，転職する。

問題 26 Ａさんは有料老人ホームに入所したばかりである。ある日，廊下を行った
り来たりしているＡさんに，Ｂ介護福祉職が声をかけた。Ａさんは，「私の部屋は
どこですか」と困った様子で答えた。Ｂ介護福祉職が，「ここから 2 つ隣の部屋で
す」と伝えると，Ａさんは，「どこですか」と不安そうな表情で聞いた。Ｂ介護福祉
職は非言語的コミュニケーションを用いて伝えることにした。
次の記述のうち，Ｂ介護福祉職が用いた非言語的コミュニケーションとして，最
も適切なものを 1 つ選びなさい。
1 ゆっくり話した。
2 大きな声で伝えた。
3 Ａさんの部屋の番号を紙に書いて渡した。
4 Ａさんに近づいた。
5 Ａさんの部屋のドアを指差した。
問題 27 次のうち，介護福祉施設におけるコンプライアンスの意味として，最も適
切なものを 1 つ選びなさい。
1 法令を遵守すること
2 給与を引き上げること
3 連携を促進すること
4 介護技術の向上に努めること
5 管理体制を強化すること

問題 28 入社して 3 か月のＡ介護福祉職は，初めて夜勤を経験したとき，排
はいせつ
泄
チェック表の記入でミスをしてしまった。起床介助で忙しい時間に記入したために，
記載箇所を間違えてしまった。Ａ介護福祉職は自身のミスを受け入れられず，落ち
込んでいる。
次の記述のうち，Ａ介護福祉職に対する支持的スーパービジョンとして，最も適
切なものを 1 つ選びなさい。
1 同僚と一緒に排
はいせつ
泄チェック表を確認する。
2 施設長から再発防止に向けた対応を指示する。
3 上司がＡ介護福祉職の気持ちの理解に努めつつ，状況を確認する。
4 看護師が利用者のその後の状況を確認する。
5 業務マニュアルを見直して，上司が必要な修正を行う。


## コミュニケーション技術

問題 29 次のうち，利用者とのコミュニケーション場面で，介護福祉職が行う自己
開示の目的として，最も適切なものを 1 つ選びなさい。
1 自己の潜在意識を活用するため
2 利用者との信頼関係を評価するため
3 利用者に自分自身の情報を知らせるため
4 利用者との信頼関係を形成するため
5 自己を深く分析し，客観的に理解するため

問題 30 Ａ介護福祉職は，認知症（dementia）のあるＢさん（80 歳，女性）と会話を
している。Ｂさんは，「私は小さい頃毎年お祭りに行くことが楽しみでね」「なんだ
か最近ひざが痛いような気がしてね」「今から何をしようかしらね」と，次々に話し
ている。Ａ介護福祉職は，Ｂさんが混乱しないように，「Ｂさん，子どもの頃の思
い出や体調のことをお話しくださっているのですね」と返答した。
次のうち，Ａ介護福祉職が行ったコミュニケーション技術として，最も適切なも
のを 1 つ選びなさい。
1 要約
2 承認
3 賞賛
4 共感
5 同意
問題 31 次の記述のうち，利用者の家族との関係づくりにおける介護福祉職の基本
姿勢として，最も適切なものを 1 つ選びなさい。
1 お互いの緊張が解けるまでじっと待つ。
2 介護福祉職のペースで話を進める。
3 利用者の意向よりも家族の意向を優先する。
4 家族への連絡は最小限にする。
5 利用者支援で協働するパートナーとして接する。

問題 32 Ａさん（80 歳，女性，要介護 3 ）は中途障害の全盲である。介護老人福祉
施設に入所している。最近，食堂の席の入れ替えがあった。Ａさんは同じテーブル
の利用者同士の会話を，自分に向けて話しかけられていると思って，応答した。し
かし，誰からも反応はなく，Ａさんは下を向いてしまった。その様子を見たＢ介護
福祉職は，Ａさんの状況に対応するために，同じテーブルの利用者にＡさんの事情
を話し，協力を求めた。
次の記述のうち，Ｂ介護福祉職が同じテーブルの利用者に協力を依頼した内容と
して，最も適切なものを 1 つ選びなさい。
1 Ａさんは疲れているので，部屋で休むように伝えてほしい。
2 Ａさんは不安なので，そっと手を握ってほしい。
3 Ａさんにもわかるように，話す相手の名前を呼んでから話しかけてほしい。
4 Ａさんが混乱するので，食堂での会話は控えてほしい。
5 Ａさんは施設の予定がわからないので，これから食事だと教えてほしい。

問題 33 Ａさん（72 歳，男性）は記憶障害があり，介護施設に入居している。ある
日，介護福祉職にＡさんが，「あの，ちょっとお願いがあるんです。ええとね，実
は，お昼ご飯をほとんど残しちゃいました…。それでね…，あ，あれかな，調理師
さんはがっかりしたかな，私はずっと食堂をやっていたんですよ。店はけっこう繁
盛していたけど閉めることになってね。あ，ええと何の話だったかな…」と話しか
けてきた。
次のうち，このときのＡさんの発言を促すための介護福祉職の応答として，最も
適切なものを 1 つ選びなさい。
1 「Ａさんは，お店を閉めたくなかったのですね」
2 「Ａさんは，どんな料理が得意だったのですか」
3 「調理師さんのことは気にしなくていいですよ」
4 「どこかからだの具合が悪いのではないですか」
5 「何かお願いがあるのではありませんか」
問題 34 次の記述のうち，客観的事実に該当するものとして，最も適切なものを 1
つ選びなさい。
1 利用者Ａは，楽しかったはずだ。
2 利用者Ａは，朝食のパンを残した。
3 利用者Ａは，何か言いたそうだった。
4 利用者Ａは，不安だったと思う。
5 利用者Ａは，退屈そうにしていた。

問題 35 次の記述のうち，介護福祉職が行う利用者の生活支援として，最も適切な
ものを 1 つ選びなさい。
1 利用者ができないことを代わりに行うことに重点を置く。
2 利用者の全体像をとらえて支援する。
3 利用者がすべてを自分一人でできるようにする。
4 利用者の生活の効率化を図ることを目標にする。
5 利用者に同情する気持ちで寄り添う。
問題 36 介護老人福祉施設における，快適な室内環境に関する次の記述のうち，最
も適切なものを 1 つ選びなさい。
1 風の通り道をつくって，換気を行う。
2 手すりは，壁紙と同じ色を使う。
3 ベッドライトの光源は，利用者の目に直接あたるように調整する。
4 カビの発生を予防するために，湿度は高く保つ。
5 靴音を小さくするために，硬い床材にする。

問題 37 パーキンソン病（Parkinson disease）の人の住まいに関する次の記述のう
ち，最も適切なものを 1 つ選びなさい。
1 玄関の段差には，スロープを設置する。
2 廊下の床には，歩幅に合わせて目印をつける。
3 リビングの床には，大きさの違うカーペットを重ねて敷く。
4 移動空間が狭くなるように，家具を配置する。
5 リビングは 1 階，浴室は 2 階にして，階段で行き来する。
問題 38 次の記述のうち，歩行が不安定になり，移動の意欲が低下している利用者
に対する介護として，最も適切なものを 1 つ選びなさい。
1 福祉用具の使用は避けて，自力での歩行を目指すように促す。
2 移動の目的を伝えるよりも，歩行機能の改善を優先する。
3 成功体験を積み重ねることができるように，達成可能な歩行の目標距離を設定す
る。
4 歩行の不安定さに合わせて，移動範囲を縮小する。
5 本人が希望しなくても，介護福祉職の判断で毎日歩くことを目標にする。
問題 39 次の記述のうち，右
み ぎ か た ま ひ
片麻痺のある利用者に対する，仰
ぎ ょ う が い
臥位（背
は い が い
臥位）から車
いすへの移乗の介護として，最も適切なものを 1 つ選びなさい。
1 利用者に右
み ぎ そ く が い
側臥位になって起き上がるように促す。
2 端座位になった利用者の左側に立つ。
3 端座位になった利用者の右側に，車いすを置く。
4 車いすのフットサポートは下げておく。
5 移乗するときは，利用者に前傾姿勢をとるように促す。

問題 40 視覚障害者の歩行時の誘導に関する次の記述のうち，最も適切なものを 1
つ選びなさい。
1 介護福祉職は，利用者の半歩後ろで背中を支えながら歩く。
2 介護福祉職は， 白
はくじょう
杖 に触れながら歩く。
3 狭い通路では，介護福祉職は利用者の後ろを歩く。
4 階段利用時は，介護福祉職は階段の前で声かけして止まる。
5 介護福祉職は，利用者が握っている上肢を振って歩く。
問題 41 身じたくの目的に関する次の記述のうち，国際生活機能分類（ＩＣＦ）にお
ける「心身機能・身体構造」の観点が考えられるものとして，最も適切なものを 1 つ
選びなさい。
1 体温を調整する。
2 身体を清潔に保つ。
3 セルフケアを行う。
4 自分を表現する。
5 周囲との人間関係を調整する。
問題 42 次の記述のうち，介護が必要な利用者への口
こうくう
腔ケアとして，最も適切なも
のを 1 つ選びなさい。
1 仰
ぎ ょ う が い
臥位（背
は い が い
臥位）で行う。
2 歯
し こ う
垢を除去するためにうがいをしてもらう。
3 歯ブラシで歯を 1 ， 2 本ずつ磨く。
4 スポンジブラシは乾いた状態で使用する。
5 部分床義歯（局部床義歯）はつけたまま行う。

問題 43 次のうち，右
み ぎ か た ま ひ
片麻痺の利用者が前開きの上着を着脱するときに介護福祉職
が行う説明として，最も適切なものを 1 つ選びなさい。
1 「脱ぐときは，左肩の衣服を下げてから，右側の袖から腕を抜きましょう」
2 「脱ぐときは，右肩の衣服を下げてから，右側の袖から腕を抜きましょう」
3 「襟元を手前にして，腿
もも
の上に置きましょう」
4 「着るときは，右袖を肘まで通してから，左袖を通しましょう」
5 「着るときは，右袖を肩まで通してから，左袖を通しましょう」
問題 44 次の記述のうち，介護老人福祉施設における食事に関する支援として，最
も適切なものを 1 つ選びなさい。
1 食堂の換気は，不要である。
2 食事中は，会話を控えるようにする。
3 食事が楽しくなるような雰囲気をつくる。
4 食べ終わった利用者の食器は，すぐに下膳する。
5 照明は，明るさを 25 ルクス（lx）以下にする。
問題 45 次の記述のうち，椅子に座って食事をするときに，利用者が食事をしやす
い姿勢を確保するための介護として，最も適切なものを 1 つ選びなさい。
1 足底を床につけてもらう。
2 テーブルと身体の間は 30 cm 離してもらう。
3 椅子に浅く座ってもらう。
4 体幹を後方に傾けてもらう。
5 顎を上げてもらう。

問題 46 咀
そ し ゃ く き の う
嚼機能が低下した利用者の食事介護に関する次の記述のうち，最も適切
なものを 1 つ選びなさい。
1 大きめのスプーンで吸い込むように食べてもらう。
2 一口量は，ティースプーンに軽く一杯を目安にする。
3 食べる順番は，介護福祉職の判断で行う。
4 スプーンは，舌の奥にのせるように入れる。
5 咀
そしゃく
嚼が始まったら，すぐに次の食べ物を口に入れる。
問題 47 Ａさん（80 歳，女性，要介護 3 ）は，介護老人福祉施設で生活している。
食事は見守りのもとでほぼ自力で摂取しているが，嚥
え ん げ き の う
下機能は低下してきている。
医師からは，食事摂取に配慮するように指導されている。ある日の昼食中，Ａさん
は食事を 1/3 ほど食べたところで箸を止め，表情がこわばり，呼吸もやや浅くなっ
た。
次の記述のうち，介護福祉職が医療職に報告すると同時に，最初に行う対応とし
て，最も適切なものを 1 つ選びなさい。
1 血圧を測定する。
2 口
こうくう
腔の状況を観察する。
3 口すぼめ呼吸を促す。
4 その場で仰
ぎ ょ う が い
臥位（背
は い が い
臥位）になってもらう。
5 すぐに薬を服用してもらう。

問題 48 ベッド上で行う陰部洗浄に関する次の記述のうち，最も適切なものを 1 つ
選びなさい。
1 滅菌手袋を使用して行う。
2 上半身はベッドの手前端に移動する。
3 バスタオルで両下肢を包む。
4 洗浄する時は，43℃のお湯を用いる。
5 終了後は，蒸しタオルで水分を拭き取る。

問題 49 腹部の清拭の方法を図に示す。矢印は拭く方向を表している。
次のうち，基本的な清拭の方法として，最も適切なものを 1 つ選びなさい。

問題 50 Ａさん（55 歳，男性，会社員）は，20 歳のときに交通事故で第 5 頚
けいずい
髄（C5）
を損傷した。現在，電動車いすを利用し，自宅で自立した生活を送っている。身体
状況は安定しているが，ときどき仙骨部に 褥
じょくそう
瘡 ができることがある。入浴は，居
宅介護（ホームヘルプサービス）を利用していて，訪問介護員（ホームヘルパー）が福
祉用具を用いて入浴介護をしている。
次のうち，Ａさんが入浴時に使用している福祉用具として，最も適切なものを 1
つ選びなさい。
1 移乗台
2 バスボード
3 入浴用リフト
4 浴槽用手すり
5 滑り止めマット

問題 51 Ａさん（85 歳，男性，要介護 3 ）は，アルツハイマー型認知症（dementia
of the Alzheimer’s type）と診断され，認知症対応型共同生活介護（認知症高齢者グ
ループホーム）で生活をしている。入所時，Ａさんは，尿意や便意はあり，自分で
トイレに行って排
はいせつ
泄できていた。最近，認知機能の低下によって，トイレ以外の場
所で排
はいせつ
泄するようになった。
次の記述のうち，Ａさんの状態に合わせた介護福祉職の対応として，最も適切な
ものを 1 つ選びなさい。
1 骨盤底筋訓練を行う。
2 紙おむつを使用する。
3 一日の水分摂取量を減らす。
4 ほかの利用者と同じ時間にトイレへ誘導する。
5 トイレの出入口に「トイレ」と書いた紙を貼る。

問題 52 次のうち，下痢をしている利用者の水分補給として，最も適切なものを 1
つ選びなさい。
1 白湯
2 牛乳
3 炭酸水
4 コーヒー
5 冷水
問題 53 Ａさん（83 歳，男性，要介護 1 ）は，一人暮らしで，少額の年金で生活し
ている。Ａさんは軽度の認知症（dementia）と診断を受けている。近所には親しく
している人が複数人いる。ある日，訪問介護員（ホームヘルパー）が訪問すると，近
所のスーパーで購入した未開封の健康食品が山積みになっていた。Ａさんが財布を
持ってきて，「買いたいものがたくさんあるが，お金が足りない。どうしたらよい
か」と訪問介護員（ホームヘルパー）に相談した。
このときの訪問介護員（ホームヘルパー）の対応に関する次の記述のうち，最も適
切なものを 1 つ選びなさい。
1 「お金は足りているから安心して大丈夫ですよ」と伝える。
2 近所の親しい人に，財布を預かってもらえるか，聞いてみる。
3 鍵付きの引き出しに財布を入れ，訪問介護員（ホームヘルパー）が鍵を管理する。
4 「お金の使い方について，一緒に考えてみませんか」と提案する。
5 健康食品のクーリング・オフを勧める。

問題 54 繊維や衣類の性質と洗濯方法に関する次の記述のうち，正しいものを 1 つ
選びなさい。
1 綿の柄物シャツには酸素系漂白剤を使う。
2 ナイロンのレインウエアは脱水時間を長くする。
3 ウールのニットセーターは乾燥機を使う。
4 レーヨンのパジャマはすすぎ時間を長くする。
5 絹のブラウスには弱アルカリ性洗剤を使う。
問題 55 Ａさん（82 歳，女性，要介護 1 ）は，訪問介護（ホームヘルプサービス）を
週 1 回利用し，生活援助を受けながら，自宅で一人暮らしをしている。調理はＡさ
ん本人が行うなど，できることは自分で行いたいと思っている。ある日，訪問介護
員（ホームヘルパー）はＡさんから買物リストを渡されて，近くのスーパーで食材を
購入してきた。
次の記述のうち，Ａさんへの生活援助における訪問介護員（ホームヘルパー）の対
応として，最も適切なものを 1 つ選びなさい。
1 依頼された食材が安かったので，リストに書かれた数より多く購入した。
2 おつりとレシート，購入した食材の確認を，Ａさんにすべて任せた。
3 冷蔵庫を開けたとき，賞味期限切れの食材があったため廃棄した。
4 買物リストは，次から訪問介護員（ホームヘルパー）が書くことを提案した。
5 購入した食材で調理しにくいものがないか，Ａさんに確認した。

問題 56 次の記述のうち，良質な睡眠のための環境づくりとして，最も適切なもの
を 1 つ選びなさい。
1 日中は，強度の高い運動を多く取り入れる。
2 夜食は，就寝直前にとる。
3 入浴は，就寝の 1 〜 2 時間前に行う。
4 眠気がなくても，決まった時間に目を閉じる。
5 寝ている間も，照明は明るくしておく。
問題 57 Ａさん（83 歳，女性，要介護 3 ）は，脳梗塞（cerebral infarction）の後遺症
で左
ひ だ り か た ま ひ
片麻痺があり，介護老人福祉施設に入所している。ある日の夜間，仰
ぎ ょ う が い
臥位（背
はい
臥
が い
位）で寝ていたＡさんが，「背中が重く感じて，眠れない」と介護福祉職に訴えた。
次の記述のうち，介護福祉職がＡさんに行う介護として，最も適切なものを 1 つ
選びなさい。
1 ファーラー位にして，左下肢にクッションを入れる。
2 両上肢の下に，クッションを入れる。
3 両
りょう
膝
し つ か ぶ
窩部に，クッションを入れる。
4 右
み ぎ そ く が い
側臥位にして，クッションを抱いてもらう。
5 右下肢の足部に，クッションを入れる。

問題 58 次の記述のうち，介護老人福祉施設で，終末期にある利用者とその家族に
行う介護福祉職の支援として，最も適切なものを 1 つ選びなさい。
1 利用者の苦しそうな姿を見せないように，家族には面会を控えてもらう。
2 利用者と家族の関係が良好でない場合は，家族と連絡を取らないようにする。
3 好きなものや食べたいものがある場合は，家族に持ってきてもらう。
4 苦痛を訴える場合は，家族から激励してもらう。
5 家族が不安になるため，体調の変化は伝えないようにする。
問題 59 次の記述のうち，施設で亡くなった利用者家族への介護福祉職の対応とし
て，最も適切なものを 1 つ選びなさい。
1 悲しみの表出があった時点からかかわりを開始する。
2 傾聴よりも励ますことを重視する。
3 悲嘆は特異な反応のため注意する。
4 故人との思い出には触れないようにする。
5 悲嘆が長期化した場合は，専門医等へ相談するように助言する。

問題 60 次のうち，固定式歩行器が適した利用者として，最も適切なものを 1 つ選
びなさい。
1 対
つ い ま ひ
麻痺で，下肢を交互に出すことができない人
2 片
か た ま ひ
麻痺があって，麻
ま ひ そ く
痺側の指関節の拘縮がある人
3 両上肢の筋力が弱く，手関節に痛みがある人
4 両手の握力が保たれていて，数秒程度の立位保持ができる人
5 右の足根骨を骨折して，右下肢に体重をかけることができない人

## 介護過程

問題 106 次のうち，介護過程における生活課題への対応として，最も適切なものを 1 つ選びなさい。

1 介護福祉職が望む支援を実現すること
2- 利用者が望む暮らしを実現すること
3 他職種が望む連携を実現すること
4 家族が望む経済状況を実現すること
5 施設が望む運営を実現すること

問題 107 次の記述のうち，短期目標に関する説明として，最も適切なものを 1 つ選びなさい。

1 介護福祉職の介護目標を設定する。
2 利用者の 1 年後の状態を記載する。
3 利用者の家族を主体にして表現する。
4- アセスメントに基づく利用者の具体的な生活課題から検討する。
5 目標達成時の介護福祉職の満足度を記載する。

問題 108 次の記述のうち，介護計画の実施に関するものとして，適切なものを 1 つ選びなさい。

1 利用者の実践状況は評価日にまとめて記録する。
2 介護福祉職が結果に満足できるまで実践を続ける。
3 介護福祉職の実践経験を積むことを目的にする。
4 他職種が立案した介護計画をチームで実践する。
5- 利用者に支援内容を説明して同意を得る。

問題 109 次のうち，サービス担当者会議にサービス管理責任者が出席する目的として，最も適切なものを 1 つ選びなさい。

1- 個別支援計画の取り組みの報告
2 障害支援区分の判定
3 支給が必要かどうかの決定
4 サービス等利用計画の説明
5 相談支援専門員への個別支援計画作成の指示

次の事例を読んで，問題 110，問題 111 について答えなさい。
〔事 例〕
Ａさん（78 歳，女性，要介護 1 ）は，軽度の認知症（dementia）があり，通所介護（デイサービス）を利用しながら一人暮らしをしている。一人娘が近くに住んでいる。最近，近所の人から娘に，「決められた日以外にごみを出しているので，そっと片付けているの」と連絡があった。\n翌日，娘がＡさんの自宅に行くと，部屋の中に弁当の空の容器がそのまま残されていた。心配した娘が同居を勧めたが，Ａさん，「これからもこの家からデイサービスに通いたい」と強い口調で言った。話し合いの結果，娘が夕方に様子を見に行くことになった。\nＡさんは，通所介護（デイサービス）を休むことなく利用していたが，ある日の迎えのとき，担当の介護福祉職に，「今日は行きたくない」と言って利用を拒否した。娘が理由を聞くと，「クイズの時間になると利用者のＢさんに，あなたの答えはいつも間違えていると何度も注意される。情けない・・・」と話した。娘はＡさんの様子を介護福祉職に伝えた。\n

問題 110 次のうち，Ａさんのニーズとして，最も適切なものを 1 つ選びなさい。

1 娘の家で同居すること
2- 自宅での生活を続けること
3 通所介護（デイサービス）を休めること
4 弁当のメニューを変更すること
5 ごみ出しを近所の人に任せること

問題 111 Ａさんの娘から連絡を受けた通所介護（デイサービス）では，介護過程の再アセスメントをすることになった。\n
次のうち，Ａさんの再アセスメントで重視すべき情報として，最も適切なものを1 つ選びなさい。

1 通所介護（デイサービス）を利用しない日の過ごし方
2- 通所介護（デイサービス）での様子
3 通所介護（デイサービス）の利用継続に関する娘の意見
4 通所介護（デイサービス）の迎えを担当した介護福祉職の印象
5 通所介護（デイサービス）以外のサービスを利用することへの意向

次の事例を読んで，問題 112，問題 113 について答えなさい。
〔事 例〕
Ａさん（50 歳，男性，障害支援区分 3 ）は，中度の知的障害がある。身体機能に問題はないが，遂行機能に障害がある。短い言葉での意思表示はできる。両親は亡くなっている。姉が近くに住んでいるが，同居は難しく，共同生活援助（グループホーム）へ入居した。入居時に短期目標を「生活のリズムを整える」と設定し，順調に進んでいた。日中は就労継続支援Ｂ型事業所に通っている。\n共同生活援助（グループホーム）の生活に慣れてきた頃，Ａさんは日中活動を休むようになった。心配した生活支援員が居室を訪ねると，Ａさんが，「昨日も，遊びに来た隣室の友人が，散らかっている部屋を見て笑った。前はきれいにできていたのに」と自信をなくしている様子であった。\n生活支援員がＡさんの居室を確認すると，趣味で集めているアニメグッズや衣服が増えていて，きれいにしていた自室内に散乱していた。\n

問題 112 次のうち，日中活動を休むようになったＡさんの状態を理解するために必要な情報として，最も適切なものを 1 つ選びなさい。

1 Ａさんの姉の家族構成
2 隣室の友人がＡさんの部屋に行った時間
3- Ａさんが自信をなくした理由
4 生活支援員がＡさんの部屋を訪ねた心情
5 Ａさんが隣室の友人と遊ぶことになった理由

問題 113 後日，カンファレンスが開かれ，短期目標についての見直しが検討された。次の記述のうち，見直された短期目標として，最も適切なものを 1 つ選びなさい。

1 趣味を変更する。
2 現在の自室の状態を維持する。
3 衣服を部屋の隅に寄せる。
4 日中活動の事業所を変更する。
5- 自室を整理整頓する。

## 総合問題

次の事例を読んで，問題 114 から問題 116 までについて答えなさい。
〔事 例〕
Ａさん（66 歳，女性）は，一人息子と二人で暮らしている。会社の趣味サークルや
地域活動に熱心に参加してきた。半年前に，長年勤めた仕事を定年退職して，継続雇
用で週 2 日の勤務になった。その頃から不眠を訴え，疲れやすく気持ちが落ち込む日
が増えてきた。しばらくすると，睡眠中に大声をあげたり，息子の部屋までふらふら
と歩いてきたり，自室のカーテンの花柄が動いて怖いと話したりするようになった。
近隣の大学病院を受診した結果，手足の震え，小刻みな歩行，顔のこわばりなどがみ
られ，レビー小体型認知症（dementia with Lewy bodies）の診断を受けた。
Ａさんは，趣味活動や自宅で息子と過ごすことを優先し，これからの生活を楽しみ
たいと考えて，仕事を辞めた。そして，安全に歩く力を維持するために介護サービス
を活用しようと考えた。Ａさんは要支援 2 の認定を受けて，介護予防通所リハビリ
テーションの利用を始めた。

問題 114 Ａさんの手足の震えは，ある体内物質の影響によって生じている。
次のうち，その体内物質に該当するものとして，最も適切なものを 1 つ選びなさ
い。
1 メラトニン（melatonin）
2 ドーパミン（dopamine）
3 アドレナリン（adrenaline）
4 コルチゾール（cortisol）
5 グルカゴン（glucagon）

問題 115 ある日，送迎のときに，介護予防通所リハビリテーション事業所のＢ介護
福祉職は，息子から，日々の症状に変動がある母を自宅で介護をするときにどのよ
うなことに注意すべきか，と聞かれた。Ｂ介護福祉職は事業所で多職種ミーティン
グを行ってから返答することにした。
次の記述のうち，Ｂ介護福祉職の息子への助言として，最も適切なものを 1 つ選
びなさい。
1 視覚的環境からの影響を防ぐために，自室のカーテンを無地のものに変更する。
2 下肢筋力を維持するために，毎日決まった時間に同じ運動をする。
3 転倒を防止するために，Ａさんの外出の機会を減らす。
4 夜間は部屋をできるだけ明るく照らすために，直接照明を用いる。
5 着脱をしやすくするために，ボタン止めの衣服を使用する。

問題 116 サービス利用開始から 2 か月後，担当介護支援専門員（介護福祉士）はモニ
タリングを行うために，Ａさんの自宅を訪れた。Ａさんは，「もっとほかの人と交
流したいが，自宅で生活しながら利用できると安心だ。とにかく息子に心配をかけ
ずに一緒に暮らしていきたい」と語った。
息子は，「最近仕事が忙しくなり，今後泊まりの出張もあるので，リハビリ以外
のサービスもうまく使ってほしい」と語った。
次のうち，Ａさんに利用を勧めるサービスとして，最も適切なものを 1 つ選びな
さい。
1 介護予防認知症対応型共同生活介護（認知症高齢者グループホーム）
2 日常生活自立支援事業
3 訪問介護（ホームヘルプサービス）
4 介護予防小規模多機能型居宅介護
5 介護予防・生活支援サービス事業の通所型サービス

次の事例を読んで，問題 117 から問題 119 までについて答えなさい。
〔事 例〕
Ａさん（85 歳，女性，要介護 1 ）は，Ｂ住居型有料老人ホームで暮らしている。子
どもはなく，親族もいない。Ａさんは現在，外部の事業所から訪問介護サービスを週
2 回利用している。Ａさんは駐車場を経営していて，毎月その収入がある。
最近，Ｃ訪問介護員（ホームヘルパー）は，Ａさんの居室内の冷蔵庫の中に同じ食材
がたくさん入っていることが多く，気になっていた。ある日，Ｃ訪問介護員（ホーム
ヘルパー）がＡさんに尋ねると，「近所のスーパーに買い物に行くのが楽しみだが，冷
蔵庫の中に何があるのか忘れてしまい，同じものばかり買ってしまう」と答えた。ま
た，「今は，毎月振り込まれる駐車場収入の管理ができているが，今後管理できなく
なることが不安だ」と話した。その後，Ａさんは，初期のアルツハイマー型認知症
（dementia of the Alzheimer’s type）の診断を受けた。

問題 117 次のうち，Ａさんが不安に思っている駐車場収入の管理について，訪問介
護事業所のサービス提供責任者がＡさんに提案する制度として，最も適切なものを
1 つ選びなさい。
1 成年後見制度
2 生活保護制度
3 老齢年金制度
4 継続雇用制度
5 後期高齢者医療制度

問題 118 その後，Ａさんは認知症（dementia）が進行することを心配し，介護支援
専門員（ケアマネジャー）に相談して，同じ市内のＤ介護付き有料老人ホームに転居
することになった。
転居してから 2 年後，Ａさんの認知症（dementia）の症状は進行してきた。Ａさ
んの担当となったＥ介護福祉職はサービス担当者会議で，「現在，Ａさんの，認知
症高齢者の日常生活自立度判定基準は，ランクⅢａと考えられる。そこで，このラ
ンクに合った介護計画を立案したい」と提案し，他職種の承諾を得た。
次のうち，Ａさんの介護計画立案時にＥ介護福祉職が意識する，認知症高齢者の
日常生活自立度判定基準Ⅲａに該当する状態として，最も適切なものを 1 つ選びな
さい。
1 日常生活が自立している状態
2 見守りがあれば自立できる状態
3 日中を中心に意思疎通の困難さがみられ，介護を必要とする状態
4 意思疎通の困難さが頻繁にみられ，常に介護を必要とする状態
5 専門医療の導入が必要な状態

問題 119 Ｄ介護付き有料老人ホームに転居してから 3 年が経過した。Ａさんの認知
症（dementia）の症状は，さらに進行してきた。Ｄ介護付き有料老人ホームでは，
施設の方針として，新たにパーソン・センタード・ケアを取り入れることになった。
次の記述のうち，Ｅ介護福祉職が介護計画を見直すときの方向性として，最も適
切なものを 1 つ選びなさい。
1 認知症（dementia）の人の共通点に着目したケアマニュアルをつくる。
2 認知症（dementia）を治療する。
3 認知症（dementia）の人のその人らしさを支える。
4 認知症（dementia）の人を特別な存在として保護する。
5 行動・心理症状（ＢＰＳＤ）をなくす。


次の事例を読んで，問題 120 から問題 122 までについて答えなさい。
〔事 例〕
Ａさん（42 歳，男性）は，知的障害がある。父親（72 歳）と二人暮らしをしている。
半年前，Ａさんに血便がみられたため病院を受診したところ，大腸がん（colorectal
cancer）と診断され，Ｓ状結腸ストーマを造設した。パウチの交換に支援が必要とな
り，退院後は父親が自宅で介護をしていた。父親の介護負担が大きくなったため，居
宅介護（ホームヘルプサービス）を利用することになった。

問題 120 次のうち，Ａさんの正常時の便の性状として，最も適切なものを 1 つ選び
なさい。
1 水様から 粥
じゅくじょう
状
2 流動状から液状
3 半流動から 粥
じゅくじょう
状
4 泥状から軟便
5 軟便から固形状
問題 121 ある日，訪問介護員（ホームヘルパー）にＡさんから，「今度，父親と温泉
に行くことになったが，便のにおいが気になる」と相談があった。
次のうち，訪問介護員（ホームヘルパー）がＡさんに勧める食品として，最も適切
なものを 1 つ選びなさい。
1 チーズ
2 たまねぎ
3 ヨーグルト
4 にら
5 アスパラガス

問題 122 ある日，訪問介護員（ホームヘルパー）がＡさんの自宅を訪問したところ，
Ａさんの父親から，「地震のニュースを見たら，知的障害があり，ストーマの管理
が必要な息子に対する災害時の対応が心配になった」と相談があった。訪問介護員
（ホームヘルパー）は，相談支援専門員に状況を報告し，相談支援専門員とともにほ
かの利用者家族に確認したところ，同様に災害時の不安を感じている親が多く，こ
の地域では個別避難計画の作成が遅れていることがわかった。そこで，訪問介護員
（ホームヘルパー）はこの課題を地域の課題としてとらえ，サービス提供責任者や相
談支援専門員とともに対応することを確認した。
次のうち，この地域課題の検討を働きかける場として，最も適切なものを 1 つ選
びなさい。
1 協議会
2 運営適正化委員会
3 介護保険審査会
4 障害者政策委員会
5 地方更生保護委員会
（注） 「協議会」とは，障害者の日常生活及び社会生活を総合的に支援するための法律
第 89 条の 3 第 1 項に規定するものである。
Ｃ パ ー ト
44
（総合問題 4 ）
次の事例を読んで，問題 123 から問題 125 までについて答えなさい。
〔事 例〕
Ａさん（50 歳，男性，障害支援区分 4 ）は， 1 年前の交通事故の後遺症で，右
み ぎ か た ま ひ
片麻痺，
高次脳機能障害（higher brain dysfunction），失語症（aphasia）となった。現在は障害
者支援施設で生活している。日中は，車いすに座って過ごしているが，すぐに右肩が
下がり上半身は右へ傾いた姿勢になる。ある日，Ｂ介護福祉職がＡさんに姿勢の傾き
を直す方法を伝えようとすると，Ａさんは大声でどなり，物を投げた。Ｂ介護福祉職
は，以前からＡさんとのコミュニケーションに悩んでいたため，Ｃ介護主任に相談す
ることにした。Ｃ介護主任の問いかけに答えるなかで，Ｂ介護福祉職は自分自身の言
動を振り返ることができ，Ａさんに伝わらない焦りと，子どもに言い聞かせるような
口調が，Ａさんの感情を害していたことに気づいた。その後，コミュニケーション方
法を工夫し，Ａさんに姿勢の傾きを直す方法を説明し，同意を得ることができた。
毎週，Ａさんは妻との面会を楽しみにしている。しかし，妻はＡさんの将来に不安
を感じて，Ｂ介護福祉職に，「夫の障害について，情報交換や勉強がしたい。そのよ
うなところがあれば紹介してほしい」と相談した。

問題 123 次のうち，Ｃ介護主任がＢ介護福祉職への対応に用いた手法として，最も
適切なものを 1 つ選びなさい。
1 コンサルテーション（consultation）
2 コーチング（coaching）
3 フォロワーシップ（followership）
4 ティーチング（teaching）
5 メンバーシップ（membership）
問題 124 Ｂ介護福祉職は，Ａさんが車いすで良肢位を保つことができるように，
クッションを使用することにした。まず，Ｂ介護福祉職はＡさんの上半身を起こし
深く座り直してもらった。
次のうち，Ｂ介護福祉職がクッションを挿入する位置として，最も適切なものを
1 つ選びなさい。
1 背中とバックサポートの間
2 左
ひだりだいたいぶ
大腿部と座面の間
3 両
りょうかたい
下腿とレッグサポートの間
4 右
み ぎ だ い た い ぶ
大腿部と左
ひだりだいたいぶ
大腿部の間
5 右上肢と右アームサポートの間


問題 125 妻の相談を受けたＢ介護福祉職がサービス管理責任者に報告をしたところ，
ある社会資源を紹介することになった。
次のうち，Ｂ介護福祉職が妻に紹介した社会資源として，最も適切なものを 1 つ
選びなさい。
1 福祉事務所
2 公共職業安定所（ハローワーク）
3 家族会
4 地域包括支援センター
5 地域障害者職業センター


